/*
 Highcharts JS v2.1.7 (2011-10-19)

 (c) 2009-2011 Torstein H?nsi

 License: www.highcharts.com/license
*/
(function(){function F(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function K(a,b){return parseInt(a,b||10)}function Ya(a){return typeof a==="string"}function xa(a){return typeof a==="object"}function ca(a){return typeof a==="number"}function ob(a){return U.log(a)/U.LN10}function pb(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function q(a){return a!==oa&&a!==null}function G(a,b,c){var d,e;if(Ya(b))q(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(q(b)&&
xa(b))for(d in b)a.setAttribute(d,b[d]);return e}function yb(a){return Object.prototype.toString.call(a)==="[object Array]"?a:[a]}function n(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],typeof c!=="undefined"&&c!==null)return c}function A(a,b){if(Lb&&b&&b.opacity!==oa)b.filter="alpha(opacity="+b.opacity*100+")";F(a.style,b)}function pa(a,b,c,d,e){a=C.createElement(a);b&&F(a,b);e&&A(a,{padding:0,border:qa,margin:0});c&&A(a,c);d&&d.appendChild(a);return a}function $(a,b){var c=function(){};
c.prototype=new a;F(c.prototype,b);return c}function mc(a,b,c,d){var e=ra.lang,f=isNaN(b=ya(b))?2:b,b=c===void 0?e.decimalPoint:c,d=d===void 0?e.thousandsSep:d,e=a<0?"-":"",c=String(K(a=ya(+a||0).toFixed(f))),g=c.length>3?c.length%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+ya(a-c).toFixed(f).slice(2):"")}function nc(a){for(var b={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a;)b.left+=a.offsetLeft,b.top+=a.offsetTop,a!==C.body&&a!==C.documentElement&&
(b.left-=a.scrollLeft,b.top-=a.scrollTop),a=a.offsetParent;return b}function oc(){this.symbol=this.color=0}function Bc(a,b,c,d,e,f,g){var h=g.x,g=g.y,i=h-a+c-25,j=g-b+d+10,m;i<7&&(i=c+h+15);i+a>c+e&&(i-=i+a-(c+e),j-=b,m=true);j<5?(j=5,m&&g>=j&&g<=j+b&&(j=g+b-5)):j+b>d+f&&(j=d+f-b-5);return{x:i,y:j}}function pc(a,b){var c=a.length,d;for(d=0;d<c;d++)a[d].ss_i=d;a.sort(function(a,c){var d=b(a,c);return d===0?a.ss_i-c.ss_i:d});for(d=0;d<c;d++)delete a[d].ss_i}function zb(a){for(var b in a)a[b]&&a[b].destroy&&
a[b].destroy(),delete a[b]}function qb(a,b){Ab=n(a,b.animation)}function Bb(){var a=ra.global.useUTC;Mb=a?Date.UTC:function(a,c,d,e,f,g){return(new Date(a,c,n(d,1),n(e,0),n(f,0),n(g,0))).getTime()};Zb=a?"getUTCMinutes":"getMinutes";$b=a?"getUTCHours":"getHours";ac=a?"getUTCDay":"getDay";Cb=a?"getUTCDate":"getDate";Nb=a?"getUTCMonth":"getMonth";Ob=a?"getUTCFullYear":"getFullYear";qc=a?"setUTCMinutes":"setMinutes";rc=a?"setUTCHours":"setHours";bc=a?"setUTCDate":"setDate";sc=a?"setUTCMonth":"setMonth";
tc=a?"setUTCFullYear":"setFullYear"}function Pb(a){Za||(Za=pa($a));a&&Za.appendChild(a);Za.innerHTML=""}function ab(){}function Db(a,b){function c(a){function b(a,c){this.pos=a;this.minor=c;this.isNew=true;c||this.addLabel()}function c(a){if(a)this.options=a,this.id=a.id;return this}function d(a,b,c,e){this.isNegative=b;this.options=a;this.x=c;this.stack=e;this.alignOptions={align:a.align||(M?b?"left":"right":"center"),verticalAlign:a.verticalAlign||(M?"middle":b?"bottom":"top"),y:n(a.y,M?4:b?14:
-6),x:n(a.x,M?b?-6:6:0)};this.textAlign=a.textAlign||(M?b?"right":"left":"center")}function e(){var a=[],b=[],c;Ba=Ga=null;A=[];l(V,function(e){c=false;l(["xAxis","yAxis"],function(a){if(e.isCartesian&&(a==="xAxis"&&p||a==="yAxis"&&!p)&&(e.options[a]===s.index||e.options[a]===oa&&s.index===0))e[a]=ha,A.push(e),c=true});!e.visible&&o.ignoreHiddenSeries&&(c=false);if(c){var f,g,h,i,j,k;if(!p){f=e.options.stacking;db=f==="percent";if(f)j=e.options.stack,i=e.type+n(j,""),k="-"+i,e.stackKey=i,g=a[i]||
[],a[i]=g,h=b[k]||[],b[k]=h;db&&(Ba=0,Ga=99)}e.isCartesian&&(l(e.data,function(a){var b=a.x,c=a.y,e=c<0,m=e?h:g,Eb=e?k:i;Ba===null&&(Ba=Ga=a[E]);p?b>Ga?Ga=b:b<Ba&&(Ba=b):q(c)&&(f&&(m[b]=q(m[b])?m[b]+c:c),c=m?m[b]:c,a=n(a.low,c),db||(c>Ga?Ga=c:a<Ba&&(Ba=a)),f&&(v[Eb]||(v[Eb]={}),v[Eb][b]||(v[Eb][b]=new d(s.stackLabels,e,b,j)),v[Eb][b].setTotal(c)))}),/(area|column|bar)/.test(e.type)&&!p&&(Ba>=0?(Ba=0,ga=true):Ga<0&&(Ga=0,ia=true)))}})}function f(a,b){var c,d;X=b?1:U.pow(10,Ha(U.log(a)/U.LN10));c=a/
X;if(!b&&(b=[1,2,2.5,5,10],s.allowDecimals===false||N))X===1?b=[1,2,5,10]:X<=0.1&&(b=[1/X]);for(d=0;d<b.length;d++)if(a=b[d],c<=(b[d]+(b[d+1]||b[d]))/2)break;a*=X;return a}function g(a){var b;b=a;X=n(X,U.pow(10,Ha(U.log(la)/U.LN10)));X<1&&(b=y(1/X)*10,b=y(a*b)/b);return b}function h(){var a,b,c,d,e=s.tickInterval,i=s.tickPixelInterval;a=s.maxZoom||(p&&!q(s.min)&&!q(s.max)?Ka(k.smallestInterval*5,Ga-Ba):null);t=r?S:O;R?(c=k[p?"xAxis":"yAxis"][s.linkedTo],d=c.getExtremes(),J=n(d.min,d.dataMin),L=n(d.max,
d.dataMax)):(J=n(Qa,s.min,Ba),L=n(Wa,s.max,Ga));N&&(J=ob(J),L=ob(L));L-J<a&&(d=(a-L+J)/2,J=W(J-d,n(s.min,J-d),Ba),L=Ka(J+a,n(s.max,J+a),Ga));if(!ta&&!db&&!R&&q(J)&&q(L)){a=L-J||1;if(!q(s.min)&&!q(Qa)&&ba&&(Ba<0||!ga))J-=a*ba;if(!q(s.max)&&!q(Wa)&&fa&&(Ga>0||!ia))L+=a*fa}la=J===L?1:R&&!e&&i===c.options.tickPixelInterval?c.tickInterval:n(e,ta?1:(L-J)*i/t);!Qb&&!q(s.tickInterval)&&(la=f(la));ha.tickInterval=la;qa=s.minorTickInterval==="auto"&&la?la/5:s.minorTickInterval;if(Qb){P=[];var e=ra.global.useUTC,
j=1E3/La,m=6E4/La,sa=36E5/La,i=864E5/La;a=6048E5/La;d=2592E6/La;var Ua=31556952E3/La,v=[["second",j,[1,2,5,10,15,30]],["minute",m,[1,2,5,10,15,30]],["hour",sa,[1,2,3,4,6,8,12]],["day",i,[1,2]],["week",a,[1,2]],["month",d,[1,2,3,4,6]],["year",Ua,null]],w=v[6],l=w[1],u=w[2];for(c=0;c<v.length;c++)if(w=v[c],l=w[1],u=w[2],v[c+1]&&la<=(l*u[u.length-1]+v[c+1][1])/2)break;l===Ua&&la<5*l&&(u=[1,2,5]);v=f(la/l,u);u=new Date(J*La);u.setMilliseconds(0);l>=j&&u.setSeconds(l>=m?0:v*Ha(u.getSeconds()/v));if(l>=
m)u[qc](l>=sa?0:v*Ha(u[Zb]()/v));if(l>=sa)u[rc](l>=i?0:v*Ha(u[$b]()/v));if(l>=i)u[bc](l>=d?1:v*Ha(u[Cb]()/v));l>=d&&(u[sc](l>=Ua?0:v*Ha(u[Nb]()/v)),b=u[Ob]());l>=Ua&&(b-=b%v,u[tc](b));if(l===a)u[bc](u[Cb]()-u[ac]()+s.startOfWeek);c=1;b=u[Ob]();j=u.getTime()/La;m=u[Nb]();for(sa=u[Cb]();j<L&&c<S;)P.push(j),l===Ua?j=Mb(b+c*v,0)/La:l===d?j=Mb(b,m+c*v)/La:!e&&(l===i||l===a)?j=Mb(b,m,sa+c*v*(l===i?1:7)):j+=l*v,c++;P.push(j);Ca=s.dateTimeLabelFormats[w[0]]}else{c=g(Ha(J/la)*la);b=g(cc(L/la)*la);P=[];for(c=
g(c);c<=b;)P.push(c),c=g(c+la)}if(!R){if(ta||p&&k.hasColumn){b=(ta?1:la)*0.5;if(ta||!q(n(s.min,Qa)))J-=b;if(ta||!q(n(s.max,Wa)))L+=b}b=P[0];c=P[P.length-1];s.startOnTick?J=b:J>b&&P.shift();s.endOnTick?L=c:L<c&&P.pop();Va||(Va={x:0,y:0});if(!Qb&&P.length>Va[E])Va[E]=P.length}}function i(){var a,b;T=J;aa=L;e();h();I=Da;Da=t/(L-J||1);if(!p)for(a in v)for(b in v[a])v[a][b].cum=v[a][b].total;if(!ha.isDirty)ha.isDirty=J!==T||L!==aa}function j(a){a=(new c(a)).render();Y.push(a);return a}function m(){var a=
s.title,d=s.stackLabels,e=s.alternateGridColor,f=s.lineWidth,g,h,i=(g=k.hasRendered)&&q(T)&&!isNaN(T);h=A.length&&q(J)&&q(L);t=r?S:O;Da=t/(L-J||1);C=r?B:Ma;if(h||R){if(qa&&!ta)for(h=J+(P[0]-J)%qa;h<=L;h+=qa)ca[h]||(ca[h]=new b(h,true)),i&&ca[h].isNew&&ca[h].render(null,true),ca[h].isActive=true,ca[h].render();l(P,function(a,b){if(!R||a>=J&&a<=L)i&&Ia[a].isNew&&Ia[a].render(b,true),Ia[a].isActive=true,Ia[a].render(b)});e&&l(P,function(a,b){if(b%2===0&&a<L)ja[a]||(ja[a]=new c),ja[a].options={from:a,
to:P[b+1]!==oa?P[b+1]:L,color:e},ja[a].render(),ja[a].isActive=true});g||l((s.plotLines||[]).concat(s.plotBands||[]),function(a){Y.push((new c(a)).render())})}l([Ia,ca,ja],function(a){for(var b in a)a[b].isActive?a[b].isActive=false:(a[b].destroy(),delete a[b])});f&&(g=B+(u?S:0)+x,h=za-Ma-(u?O:0)+x,g=H.crispLine([ua,r?B:g,r?h:D,Z,r?va-$:g,r?h:za-Ma],f),G?G.animate({d:g}):G=H.path(g).attr({stroke:s.lineColor,"stroke-width":f,zIndex:7}).add());if(z)g=r?B:D,f=K(a.style.fontSize||12),g={low:g+(r?0:t),
middle:g+t/2,high:g+(r?t:0)}[a.align],f=(r?D+O:B)+(r?1:-1)*(u?-1:1)*Fa+(Ra===2?f:0),z[z.isNew?"attr":"animate"]({x:r?g:f+(u?S:0)+x+(a.x||0),y:r?f-(u?O:0)+x:g+(a.y||0)}),z.isNew=false;if(d&&d.enabled){var j,sa,d=ha.stackTotalGroup;if(!d)ha.stackTotalGroup=d=H.g("stack-labels").attr({visibility:Pa,zIndex:6}).translate(B,D).add();for(j in v)for(sa in a=v[j],a)a[sa].render(d)}ha.isDirty=false}function w(a){for(var b=Y.length;b--;)Y[b].id===a&&Y[b].destroy()}var p=a.isX,u=a.opposite,r=M?!p:p,Ra=r?u?0:
2:u?1:3,v={},s=Q(p?Rb:dc,[Cc,Dc,uc,Ec][Ra],a),ha=this,z,Fb=s.type,Qb=Fb==="datetime",N=Fb==="logarithmic",x=s.offset||0,E=p?"x":"y",t,Da,I,C=r?B:Ma,rb,sb,tb,cb,G,Ba,Ga,A,Qa,Wa,L=null,J=null,T,aa,ba=s.minPadding,fa=s.maxPadding,R=q(s.linkedTo),ga,ia,db,Fb=s.events,pa,Y=[],la,qa,X,P,Ia={},ca={},ja={},na,wa,Fa,Ca,ta=s.categories,Oa=s.labels.formatter||function(){var a=this.value;return Ca?Sb(Ca,a):la%1E6===0?a/1E6+"M":la%1E3===0?a/1E3+"k":!ta&&a>=1E3?mc(a,0):a},Ea=r&&s.labels.staggerLines,xa=s.reversed,
Aa=ta&&s.tickmarkPlacement==="between"?0.5:0;b.prototype={addLabel:function(){var a=this.pos,b=s.labels,c=!(a===J&&!n(s.showFirstLabel,1)||a===L&&!n(s.showLastLabel,0)),d=ta&&r&&ta.length&&!b.step&&!b.staggerLines&&!b.rotation&&S/ta.length||!r&&S/2,e=ta&&q(ta[a])?ta[a]:a,f=this.label,a=Oa.call({isFirst:a===P[0],isLast:a===P[P.length-1],dateTimeLabelFormat:Ca,value:N?U.pow(10,e):e}),d=d&&{width:W(1,y(d-2*(b.padding||10)))+ma},d=F(d,b.style);f===oa?this.label=q(a)&&c&&b.enabled?H.text(a,0,0,b.useHTML).attr({align:b.align,
rotation:b.rotation}).css(d).add(tb):null:f&&f.attr({text:a}).css(d)},getLabelSize:function(){var a=this.label;return a?(this.labelBBox=a.getBBox())[r?"height":"width"]:0},render:function(a,b){var c=!this.minor,d=this.label,e=this.pos,f=s.labels,g=this.gridLine,h=c?s.gridLineWidth:s.minorGridLineWidth,i=c?s.gridLineColor:s.minorGridLineColor,j=c?s.gridLineDashStyle:s.minorGridLineDashStyle,m=this.mark,k=c?s.tickLength:s.minorTickLength,sa=c?s.tickWidth:s.minorTickWidth||0,v=c?s.tickColor:s.minorTickColor,
l=c?s.tickPosition:s.minorTickPosition,Ua=f.step,w=b&&Ta||za,p;p=r?rb(e+Aa,null,null,b)+C:B+x+(u?(b&&Sa||va)-$-B:0);w=r?w-Ma+x-(u?O:0):w-rb(e+Aa,null,null,b)-C;if(h){e=sb(e+Aa,h,b);if(g===oa){g={stroke:i,"stroke-width":h};if(j)g.dashstyle=j;if(c)g.zIndex=1;this.gridLine=g=h?H.path(e).attr(g).add(cb):null}!b&&g&&e&&g.animate({d:e})}if(sa)l==="inside"&&(k=-k),u&&(k=-k),c=H.crispLine([ua,p,w,Z,p+(r?0:-k),w+(r?k:0)],sa),m?m.animate({d:c}):this.mark=H.path(c).attr({stroke:v,"stroke-width":sa}).add(tb);
if(d&&!isNaN(p)){p=p+f.x-(Aa&&r?Aa*Da*(xa?-1:1):0);w=w+f.y-(Aa&&!r?Aa*Da*(xa?1:-1):0);q(f.y)||(w+=K(d.styles.lineHeight)*0.9-d.getBBox().height/2);Ea&&(w+=a/(Ua||1)%Ea*16);if(Ua)d[a%Ua?"hide":"show"]();d[this.isNew?"attr":"animate"]({x:p,y:w})}this.isNew=false},destroy:function(){zb(this)}};c.prototype={render:function(){var a=this,b=a.options,c=b.label,d=a.label,e=b.width,f=b.to,g=b.from,h=b.value,i,j=b.dashStyle,m=a.svgElem,k=[],sa,v,s=b.color;v=b.zIndex;var l=b.events;N&&(g=ob(g),f=ob(f),h=ob(h));
if(e){if(k=sb(h,e),b={stroke:s,"stroke-width":e},j)b.dashstyle=j}else if(q(g)&&q(f))g=W(g,J),f=Ka(f,L),i=sb(f),(k=sb(g))&&i?k.push(i[4],i[5],i[1],i[2]):k=null,b={fill:s};else return;if(q(v))b.zIndex=v;if(m)k?m.animate({d:k},null,m.onGetPath):(m.hide(),m.onGetPath=function(){m.show()});else if(k&&k.length&&(a.svgElem=m=H.path(k).attr(b).add(),l))for(sa in j=function(b){m.on(b,function(c){l[b].apply(a,[c])})},l)j(sa);if(c&&q(c.text)&&k&&k.length&&S>0&&O>0){c=Q({align:r&&i&&"center",x:r?!i&&4:10,verticalAlign:!r&&
i&&"middle",y:r?i?16:10:i?6:-4,rotation:r&&!i&&90},c);if(!d)a.label=d=H.text(c.text,0,0).attr({align:c.textAlign||c.align,rotation:c.rotation,zIndex:v}).css(c.style).add();i=[k[1],k[4],n(k[6],k[1])];k=[k[2],k[5],n(k[7],k[2])];sa=Ka.apply(U,i);v=Ka.apply(U,k);d.align(c,false,{x:sa,y:v,width:W.apply(U,i)-sa,height:W.apply(U,k)-v});d.show()}else d&&d.hide();return a},destroy:function(){zb(this);pb(Y,this)}};d.prototype={destroy:function(){zb(this)},setTotal:function(a){this.cum=this.total=a},render:function(a){var b=
this.options.formatter.call(this);this.label?this.label.attr({text:b,visibility:Ja}):this.label=k.renderer.text(b,0,0).css(this.options.style).attr({align:this.textAlign,rotation:this.options.rotation,visibility:Ja}).add(a)},setOffset:function(a,b){var c=this.isNegative,d=ha.translate(this.total),e=ha.translate(0),e=ya(d-e),f=k.xAxis[0].translate(this.x)+a,g=k.plotHeight,c={x:M?c?d:d-e:f,y:M?g-f-b:c?g-d-e:g-d,width:M?e:b,height:M?b:e};this.label&&this.label.align(this.alignOptions,null,c).attr({visibility:Pa})}};
rb=function(a,b,c,d,e){var f=1,g=0,h=d?I:Da,d=d?T:J;h||(h=Da);c&&(f*=-1,g=t);xa&&(f*=-1,g-=f*t);b?(xa&&(a=t-a),a=a/h+d,N&&e&&(a=U.pow(10,a))):(N&&e&&(a=ob(a)),a=f*(a-d)*h+g);return a};sb=function(a,b,c){var d,e,f,a=rb(a,null,null,c),g=c&&Ta||za,h=c&&Sa||va,i,c=e=y(a+C);d=f=y(g-a-C);if(isNaN(a))i=true;else if(r){if(d=D,f=g-Ma,c<B||c>B+S)i=true}else if(c=B,e=h-$,d<D||d>D+O)i=true;return i?null:H.crispLine([ua,c,d,Z,e,f],b||0)};M&&p&&xa===oa&&(xa=true);F(ha,{addPlotBand:j,addPlotLine:j,adjustTickAmount:function(){if(Va&&
!Qb&&!ta&&!R){var a=na,b=P.length;na=Va[E];if(b<na){for(;P.length<na;)P.push(g(P[P.length-1]+la));Da*=(b-1)/(na-1);L=P[P.length-1]}if(q(a)&&na!==a)ha.isDirty=true}},categories:ta,getExtremes:function(){return{min:J,max:L,dataMin:Ba,dataMax:Ga,userMin:Qa,userMax:Wa}},getPlotLinePath:sb,getThreshold:function(a){J>a?a=J:L<a&&(a=L);return rb(a,0,1)},isXAxis:p,options:s,plotLinesAndBands:Y,getOffset:function(){var a=A.length&&q(J)&&q(L),c=0,d=0,e=s.title,f=s.labels,g=[-1,1,1,-1][Ra],h;tb||(tb=H.g("axis").attr({zIndex:7}).add(),
cb=H.g("grid").attr({zIndex:1}).add());wa=0;if(a||R)l(P,function(a){Ia[a]?Ia[a].addLabel():Ia[a]=new b(a);if(Ra===0||Ra===2||{1:"left",3:"right"}[Ra]===f.align)wa=W(Ia[a].getLabelSize(),wa)}),Ea&&(wa+=(Ea-1)*16);else for(h in Ia)Ia[h].destroy(),delete Ia[h];if(e&&e.text){if(!z)z=ha.axisTitle=H.text(e.text,0,0,e.useHTML).attr({zIndex:7,rotation:e.rotation||0,align:e.textAlign||{low:"left",middle:"center",high:"right"}[e.align]}).css(e.style).add(),z.isNew=true;c=z.getBBox()[r?"height":"width"];d=n(e.margin,
r?5:10)}x=g*(s.offset||ka[Ra]);Fa=wa+(Ra!==2&&wa&&g*s.labels[r?"y":"x"])+d;ka[Ra]=W(ka[Ra],Fa+c+g*x)},render:m,setCategories:function(b,c){ha.categories=a.categories=ta=b;l(A,function(a){a.translate();a.setTooltipPoints(true)});ha.isDirty=true;n(c,true)&&k.redraw()},setExtremes:function(a,b,c,d){c=n(c,true);da(ha,"setExtremes",{min:a,max:b},function(){Qa=a;Wa=b;c&&k.redraw(d)})},setScale:i,setTickPositions:h,translate:rb,redraw:function(){bb.resetTracker&&bb.resetTracker();m();l(Y,function(a){a.render()});
l(A,function(a){a.isDirty=true})},removePlotBand:w,removePlotLine:w,reversed:xa,stacks:v,destroy:function(){var a;Na(ha);for(a in v)zb(v[a]),v[a]=null;if(ha.stackTotalGroup)ha.stackTotalGroup=ha.stackTotalGroup.destroy();l([Ia,ca,ja,Y],function(a){zb(a)});l([G,tb,cb,z],function(a){a&&a.destroy()});G=tb=cb=z=null}});for(pa in Fb)ea(ha,pa,Fb[pa]);i()}function d(){var b={};return{add:function(c,d,e,f){b[c]||(d=H.text(d,0,0).css(a.toolbar.itemStyle).align({align:"right",x:-$-20,y:D+30}).on("click",f).attr({align:"right",
zIndex:20}).add(),b[c]=d)},remove:function(a){Pb(b[a].element);b[a]=null}}}function e(a){function b(){var a=this.points||yb(this),c=a[0].series.xAxis,d=this.x,c=c&&c.options.type==="datetime",e=Ya(d)||c,f;f=e?['<span style="font-size: 10px">'+(c?Sb("%A, %b %e, %Y",d):d)+"</span>"]:[];l(a,function(a){f.push(a.point.tooltipFormatter(e))});return f.join("<br/>")}function c(a,b){o=u?a:(2*o+a)/3;v=u?b:(v+b)/2;s.translate(o,v);lb=ya(a-o)>1||ya(b-v)>1?function(){c(a,b)}:null}function d(){if(!u){var a=k.hoverPoints;
s.hide();l(h,function(a){a&&a.hide()});a&&l(a,function(a){a.setState()});k.hoverPoints=null;u=true}}var e,f=a.borderWidth,g=a.crosshairs,h=[],i=a.style,j=a.shared,m=K(i.padding),w=f+m,u=true,p,r,o=0,v=0;i.padding=0;var s=H.g("tooltip").attr({zIndex:8}).add(),n=H.rect(w,w,0,0,a.borderRadius,f).attr({fill:a.backgroundColor,"stroke-width":f}).add(s).shadow(a.shadow),z=H.text("",m+w,K(i.fontSize)+m+w,a.useHTML).attr({zIndex:1}).css(i).add(s);s.hide();return{shared:j,refresh:function(f){var i,v,o,N=0,
q={},t=[];o=f.tooltipPos;i=a.formatter||b;q=k.hoverPoints;j?(q&&l(q,function(a){a.setState()}),k.hoverPoints=f,l(f,function(a){a.setState(wa);N+=a.plotY;t.push(a.getLabelConfig())}),v=f[0].plotX,N=y(N)/f.length,q={x:f[0].category},q.points=t,f=f[0]):q=f.getLabelConfig();q=i.call(q);e=f.series;v=j?v:f.plotX;N=j?N:f.plotY;i=y(o?o[0]:M?S-N:v);v=y(o?o[1]:M?O-v:N);o=j||!f.series.isCartesian||gb(i,v);q===false||!o?d():(u&&(s.show(),u=false),z.attr({text:q}),o=z.getBBox(),p=o.width+2*m,r=o.height+2*m,n.attr({width:p,
height:r,stroke:a.borderColor||f.color||e.color||"#606060"}),i=Bc(p,r,B,D,S,O,{x:i,y:v}),c(y(i.x-w),y(i.y-w)));if(g){g=yb(g);for(i=g.length;i--;)if(v=f.series[i?"yAxis":"xAxis"],g[i]&&v)if(v=v.getPlotLinePath(f[i?"y":"x"],1),h[i])h[i].attr({d:v,visibility:Pa});else{o={"stroke-width":g[i].width||1,stroke:g[i].color||"#C0C0C0",zIndex:2};if(g[i].dashStyle)o.dashstyle=g[i].dashStyle;h[i]=H.path(v).attr(o).add()}}},hide:d,destroy:function(){l(h,function(a){a&&a.destroy()});l([n,z,s],function(a){a&&a.destroy()});
n=z=s=null}}}function f(a){function b(a){var c,d=vc&&C.width/C.body.scrollWidth-1,e,f,g,a=a||ia.event;if(!a.target)a.target=a.srcElement;c=a.touches?a.touches.item(0):a;if(a.type!=="mousemove"||ia.opera||d)Ca=nc(I),e=Ca.left,f=Ca.top;Lb?(g=a.x,c=a.y):c.layerX===oa?(g=c.pageX-e,c=c.pageY-f):(g=a.layerX,c=a.layerY);d&&(g+=y((d+1)*e-e),c+=y((d+1)*f-f));return F(a,{chartX:g,chartY:c})}function c(a){var b={xAxis:[],yAxis:[]};l(aa,function(c){var d=c.translate,e=c.isXAxis;b[e?"xAxis":"yAxis"].push({axis:c,
value:d((M?!e:e)?a.chartX-B:O-a.chartY+D,true)})});return b}function d(){var a=k.hoverSeries,b=k.hoverPoint;if(b)b.onMouseOut();if(a)a.onMouseOut();hb&&hb.hide();ec=null}function f(){if(m){var a={xAxis:[],yAxis:[]},b=m.getBBox(),c=b.x-B,d=b.y-D;j&&(l(aa,function(e){var f=e.translate,g=e.isXAxis,h=M?!g:g,i=f(h?c:O-d-b.height,true,0,0,1),f=f(h?c+b.width:O-d,true,0,0,1);a[g?"xAxis":"yAxis"].push({axis:e,min:Ka(i,f),max:W(i,f)})}),da(k,"selection",a,fc));m=m.destroy()}k.mouseIsDown=ab=j=false;Na(C,Oa?
"touchend":"mouseup",f)}function g(a){var b=q(a.pageX)?a.pageX:a.page.x,a=q(a.pageX)?a.pageY:a.page.y;Ca&&!gb(b-Ca.left-B,a-Ca.top-D)&&d()}var h,i,j,m,w=o.zoomType,u=/x/.test(w),p=/y/.test(w),r=u&&!M||p&&M,n=p&&!M||u&&M;Tb=function(){Gb?(Gb.translate(B,D),M&&Gb.attr({width:k.plotWidth,height:k.plotHeight}).invert()):k.trackerGroup=Gb=H.g("tracker").attr({zIndex:9}).add()};Tb();if(a.enabled)k.tooltip=hb=e(a);(function(){I.onmousedown=function(a){a=b(a);!Oa&&a.preventDefault&&a.preventDefault();k.mouseIsDown=
ab=true;h=a.chartX;i=a.chartY;ea(C,Oa?"touchend":"mouseup",f)};var e=function(c){if(!c||!(c.touches&&c.touches.length>1)){c=b(c);if(!Oa)c.returnValue=false;var d=c.chartX,e=c.chartY,f=!gb(d-B,e-D);Ca||(Ca=nc(I));Oa&&c.type==="touchstart"&&(G(c.target,"isTracker")?k.runTrackerClick||c.preventDefault():!mb&&!f&&c.preventDefault());f&&(d<B?d=B:d>B+S&&(d=B+S),e<D?e=D:e>D+O&&(e=D+O));if(ab&&c.type!=="touchstart"){if(j=Math.sqrt(Math.pow(h-d,2)+Math.pow(i-e,2)),j>10){if(ub&&(u||p)&&gb(h-B,i-D))m||(m=H.rect(B,
D,r?1:S,n?1:O,0).attr({fill:o.selectionMarkerFill||"rgba(69,114,167,0.25)",zIndex:7}).add());m&&r&&(d-=h,m.attr({width:ya(d),x:(d>0?0:d)+h}));m&&n&&(e-=i,m.attr({height:ya(e),y:(e>0?0:e)+i}))}}else if(!f){var g,e=k.hoverPoint,d=k.hoverSeries,l,w,z=va,q=M?c.chartY:c.chartX-B;if(hb&&a.shared){g=[];l=V.length;for(w=0;w<l;w++)if(V[w].visible&&V[w].tooltipPoints.length)c=V[w].tooltipPoints[q],c._dist=ya(q-c.plotX),z=Ka(z,c._dist),g.push(c);for(l=g.length;l--;)g[l]._dist>z&&g.splice(l,1);if(g.length&&g[0].plotX!==
ec)hb.refresh(g),ec=g[0].plotX}if(d&&d.tracker&&(c=d.tooltipPoints[q])&&c!==e)c.onMouseOver()}return f||!ub}};I.onmousemove=e;ea(I,"mouseleave",d);ea(C,"mousemove",g);I.ontouchstart=function(a){if(u||p)I.onmousedown(a);e(a)};I.ontouchmove=e;I.ontouchend=function(){j&&d()};I.onclick=function(a){var d=k.hoverPoint,a=b(a);a.cancelBubble=true;if(!j)if(d&&G(a.target,"isTracker")){var e=d.plotX,f=d.plotY;F(d,{pageX:Ca.left+B+(M?S-f:e),pageY:Ca.top+D+(M?O-e:f)});da(d.series,"click",F(a,{point:d}));d.firePointEvent("click",
a)}else F(a,c(a)),gb(a.chartX-B,a.chartY-D)&&da(k,"click",a);j=false}})();Bb=setInterval(function(){lb&&lb()},32);F(this,{zoomX:u,zoomY:p,resetTracker:d,destroy:function(){if(k.trackerGroup)k.trackerGroup=Gb=k.trackerGroup.destroy();Na(C,"mousemove",g);I.onclick=I.onmousedown=I.onmousemove=I.ontouchstart=I.ontouchend=I.ontouchmove=null}})}function g(a){var b=a.type||o.type||o.defaultSeriesType,c=ja[b],d=k.hasRendered;if(d)if(M&&b==="column")c=ja.bar;else if(!M&&b==="bar")c=ja.column;b=new c;b.init(k,
a);!d&&b.inverted&&(M=true);if(b.isCartesian)ub=b.isCartesian;V.push(b);return b}function h(){o.alignTicks!==false&&l(aa,function(a){a.adjustTickAmount()});Va=null}function i(a){var b=k.isDirtyLegend,c,d=k.isDirtyBox,e=V.length,f=e,g=k.clipRect;for(qb(a,k);f--;)if(a=V[f],a.isDirty&&a.options.stacking){c=true;break}if(c)for(f=e;f--;)if(a=V[f],a.options.stacking)a.isDirty=true;l(V,function(a){a.isDirty&&(a.cleanData(),a.getSegments(),a.options.legendType==="point"&&(b=true))});if(b&&Hb.renderLegend)Hb.renderLegend(),
k.isDirtyLegend=false;ub&&(Ub||(Va=null,l(aa,function(a){a.setScale()})),h(),Ib(),l(aa,function(a){if(a.isDirty||d)a.redraw(),d=true}));d&&(gc(),Tb(),g&&(Jb(g),g.animate({width:k.plotSizeX,height:k.plotSizeY})));l(V,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});bb&&bb.resetTracker&&bb.resetTracker();da(k,"redraw")}function j(){var b=a.xAxis||{},d=a.yAxis||{},e,b=yb(b);l(b,function(a,b){a.index=b;a.isX=true});d=yb(d);l(d,function(a,b){a.index=b});aa=b.concat(d);k.xAxis=
[];k.yAxis=[];aa=vb(aa,function(a){e=new c(a);k[e.isXAxis?"xAxis":"yAxis"].push(e);return e});h()}function m(b,c){T=Q(a.title,b);ga=Q(a.subtitle,c);l([["title",b,T],["subtitle",c,ga]],function(a){var b=a[0],c=k[b],d=a[1],a=a[2];c&&d&&(c=c.destroy());a&&a.text&&!c&&(k[b]=H.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:1}).css(a.style).add().align(a,false,ba))})}function w(){X=o.renderTo;Fa=wb+hc++;Ya(X)&&(X=C.getElementById(X));X.innerHTML="";X.offsetWidth||(R=X.cloneNode(0),
A(R,{position:ib,top:"-9999px",display:""}),C.body.appendChild(R));na=(R||X).offsetWidth;ca=(R||X).offsetHeight;k.chartWidth=va=o.width||na||600;k.chartHeight=za=o.height||(ca>19?ca:400);k.container=I=pa($a,{className:"highcharts-container"+(o.className?" "+o.className:""),id:Fa},F({position:wc,overflow:Ja,width:va+ma,height:za+ma,textAlign:"left"},o.style),R||X);k.renderer=H=o.forExport?new Vb(I,va,za,true):new Wb(I,va,za);var a,b;xc&&I.getBoundingClientRect&&(a=function(){A(I,{left:0,top:0});b=
I.getBoundingClientRect();A(I,{left:-(b.left-K(b.left))+ma,top:-(b.top-K(b.top))+ma})},a(),ea(ia,"resize",a),ea(k,"destroy",function(){Na(ia,"resize",a)}))}function N(){function a(){var c=o.width||X.offsetWidth,d=o.height||X.offsetHeight;if(c&&d){if(c!==na||d!==ca)clearTimeout(b),b=setTimeout(function(){ic(c,d,false)},100);na=c;ca=d}}var b;ea(ia,"resize",a);ea(k,"destroy",function(){Na(ia,"resize",a)})}function x(){da(k,"endResize",null,function(){Ub-=1})}function t(){var b=a.labels,c=a.credits,e;
m();Hb=k.legend=new Yb;Ib();l(aa,function(a){a.setTickPositions(true)});h();Ib();gc();ub&&l(aa,function(a){a.render()});if(!k.seriesGroup)k.seriesGroup=H.g("series-group").attr({zIndex:3}).add();l(V,function(a){a.translate();a.setTooltipPoints();a.render()});b.items&&l(b.items,function(){var a=F(b.style,this.style),c=K(a.left)+B,d=K(a.top)+D+12;delete a.left;delete a.top;H.text(this.html,c,d).attr({zIndex:2}).css(a).add()});if(!k.toolbar)k.toolbar=d();if(c.enabled&&!k.credits)e=c.href,k.credits=H.text(c.text,
0,0).on("click",function(){if(e)location.href=e}).attr({align:c.position.align,zIndex:8}).css(c.style).add().align(c.position);Tb();k.hasRendered=true;R&&(X.appendChild(I),Pb(R))}function r(){var a,b=I&&I.parentNode;if(k!==null){da(k,"destroy");Na(ia,"unload",r);Na(k);for(a=aa.length;a--;)aa[a]=aa[a].destroy();for(a=V.length;a--;)V[a]=V[a].destroy();l("title,subtitle,seriesGroup,clipRect,credits,tracker".split(","),function(a){var b=k[a];b&&(k[a]=b.destroy())});l([xb,Hb,hb,H,bb],function(a){a&&a.destroy&&
a.destroy()});xb=Hb=hb=H=bb=null;if(I)I.innerHTML="",Na(I),b&&b.removeChild(I),I=null;clearInterval(Bb);for(a in k)delete k[a];k=null}}function E(){!Kb&&ia==ia.top&&C.readyState!=="complete"?C.attachEvent("onreadystatechange",function(){C.detachEvent("onreadystatechange",E);C.readyState==="complete"&&E()}):(w(),jc(),kc(),l(a.series||[],function(a){g(a)}),k.inverted=M=n(M,a.chart.inverted),j(),k.render=t,k.tracker=bb=new f(a.tooltip),t(),da(k,"load"),b&&b.apply(k,[k]),l(k.callbacks,function(a){a.apply(k,
[k])}))}Rb=Q(Rb,ra.xAxis);dc=Q(dc,ra.yAxis);ra.xAxis=ra.yAxis=null;var a=Q(ra,a),o=a.chart,z=o.margin,z=xa(z)?z:[z,z,z,z],p=n(o.marginTop,z[0]),u=n(o.marginRight,z[1]),Da=n(o.marginBottom,z[2]),Wa=n(o.marginLeft,z[3]),Qa=o.spacingTop,cb=o.spacingRight,db=o.spacingBottom,fa=o.spacingLeft,ba,T,ga,D,$,Ma,B,ka,X,R,I,Fa,na,ca,va,za,Sa,Ta,xb,Aa,Xa,Ea,k=this,mb=(z=o.events)&&!!z.click,Za,gb,hb,ab,jb,nb,kb,O,S,bb,Gb,Tb,Hb,eb,fb,Ca,ub=o.showAxes,Ub=0,aa=[],Va,V=[],M,H,lb,Bb,ec,gc,Ib,jc,kc,ic,fc,Db,Yb=function(){function a(b,
c){var d=b.legendItem,e=b.legendLine,g=b.legendSymbol,h=p.color,i=c?f.itemStyle.color:h,j=c?b.color:h,h=c?b.pointAttr[Y]:{stroke:h,fill:h};d&&d.css({fill:i});e&&e.attr({stroke:j});g&&g.attr(h)}function b(a,c,d){var e=a.legendItem,f=a.legendLine,g=a.legendSymbol,a=a.checkbox;e&&e.attr({x:c,y:d});f&&f.translate(c,d-4);g&&g.attr({x:c+g.xOff,y:d+g.yOff});if(a)a.x=c,a.y=d}function c(){l(j,function(a){var b=a.checkbox,c=E.alignAttr;b&&A(b,{left:c.translateX+a.legendItemWidth+b.x-40+ma,top:c.translateY+
b.y-11+ma})})}function d(c){var e,j,m,k,l=c.legendItem;k=c.series||c;var o=k.options,t=o&&o.borderWidth||0;if(!l){k=/^(bar|pie|area|column)$/.test(k.type);c.legendItem=l=H.text(f.labelFormatter.call(c),0,0).css(c.visible?w:p).on("mouseover",function(){c.setState(wa);l.css(u)}).on("mouseout",function(){l.css(c.visible?w:p);c.setState()}).on("click",function(){var a=function(){c.setVisible()};c.firePointEvent?c.firePointEvent("legendItemClick",null,a):da(c,"legendItemClick",null,a)}).attr({zIndex:2}).add(E);
if(!k&&o&&o.lineWidth){var x={"stroke-width":o.lineWidth,zIndex:2};if(o.dashStyle)x.dashstyle=o.dashStyle;c.legendLine=H.path([ua,-h-i,0,Z,-i,0]).attr(x).add(E)}k?e=H.rect(j=-h-i,m=-11,h,12,2).attr({zIndex:3}).add(E):o&&o.marker&&o.marker.enabled&&(e=H.symbol(c.symbol,j=-h/2-i,m=-4,o.marker.radius).attr({zIndex:3}).add(E));if(e)e.xOff=j+t%2/2,e.yOff=m+t%2/2;c.legendSymbol=e;a(c,c.visible);if(o&&o.showCheckbox)c.checkbox=pa("input",{type:"checkbox",checked:c.selected,defaultChecked:c.selected},f.itemCheckboxStyle,
I),ea(c.checkbox,"click",function(a){da(c,"checkboxClick",{checked:a.target.checked},function(){c.select()})})}e=l.getBBox();j=c.legendItemWidth=f.itemWidth||h+i+e.width+r;N=e.height;if(g&&s-n+j>(B||va-2*r-n))s=n,z+=N;q=z;b(c,s,z);g?s+=j:z+=N;y=B||W(g?s-n:j,y)}function e(){s=n;z=o;q=y=0;E||(E=H.g("legend").attr({zIndex:7}).add());j=[];l(D,function(a){var b=a.options;b.showInLegend&&(j=j.concat(b.legendType==="point"?a.data:a))});pc(j,function(a,b){return(a.options.legendIndex||0)-(b.options.legendIndex||
0)});C&&j.reverse();l(j,d);eb=B||y;fb=q-o+N;if(x||Da){eb+=2*r;fb+=2*r;if(t){if(eb>0&&fb>0)t[t.isNew?"attr":"animate"](t.crisp(null,null,null,eb,fb)),t.isNew=false}else t=H.rect(0,0,eb,fb,f.borderRadius,x||0).attr({stroke:f.borderColor,"stroke-width":x||0,fill:Da||qa}).add(E).shadow(f.shadow),t.isNew=true;t[j.length?"show":"hide"]()}for(var a=["left","right","top","bottom"],b,g=4;g--;)b=a[g],m[b]&&m[b]!=="auto"&&(f[g<2?"align":"verticalAlign"]=b,f[g<2?"x":"y"]=K(m[b])*(g%2?-1:1));j.length&&E.align(F(f,
{width:eb,height:fb}),true,ba);Ub||c()}var f=k.options.legend;if(f.enabled){var g=f.layout==="horizontal",h=f.symbolWidth,i=f.symbolPadding,j,m=f.style,w=f.itemStyle,u=f.itemHoverStyle,p=f.itemHiddenStyle,r=K(m.padding),o=18,n=4+r+h+i,s,z,q,N=0,t,x=f.borderWidth,Da=f.backgroundColor,E,y,B=f.width,D=k.series,C=f.reversed;e();ea(k,"endResize",c);return{colorizeItem:a,destroyItem:function(a){var b=a.checkbox;l(["legendItem","legendLine","legendSymbol"],function(b){a[b]&&a[b].destroy()});b&&Pb(a.checkbox)},
renderLegend:e,destroy:function(){t&&(t=t.destroy());E&&(E=E.destroy())}}}};gb=function(a,b){return a>=0&&a<=S&&b>=0&&b<=O};Db=function(){da(k,"selection",{resetSelection:true},fc);k.toolbar.remove("zoom")};fc=function(a){var b=ra.lang,c=k.pointCount<100;k.toolbar.add("zoom",b.resetZoom,b.resetZoomTitle,Db);!a||a.resetSelection?l(aa,function(a){a.setExtremes(null,null,false,c)}):l(a.xAxis.concat(a.yAxis),function(a){var b=a.axis;k.tracker[b.isXAxis?"zoomX":"zoomY"]&&b.setExtremes(a.min,a.max,false,
c)});i()};Ib=function(){var b=a.legend,c=n(b.margin,10),d=b.x,e=b.y,f=b.align,g=b.verticalAlign,h;jc();if((k.title||k.subtitle)&&!q(p))(h=W(k.title&&!T.floating&&!T.verticalAlign&&T.y||0,k.subtitle&&!ga.floating&&!ga.verticalAlign&&ga.y||0))&&(D=W(D,h+n(T.margin,15)+Qa));b.enabled&&!b.floating&&(f==="right"?q(u)||($=W($,eb-d+c+cb)):f==="left"?q(Wa)||(B=W(B,eb+d+c+fa)):g==="top"?q(p)||(D=W(D,fb+e+c+Qa)):g==="bottom"&&(q(Da)||(Ma=W(Ma,fb-e+c+db))));ub&&l(aa,function(a){a.getOffset()});q(Wa)||(B+=ka[3]);
q(p)||(D+=ka[0]);q(Da)||(Ma+=ka[2]);q(u)||($+=ka[1]);kc()};ic=function(a,b,c){var d=k.title,e=k.subtitle;Ub+=1;qb(c,k);Ta=za;Sa=va;k.chartWidth=va=y(a);k.chartHeight=za=y(b);A(I,{width:va+ma,height:za+ma});H.setSize(va,za,c);S=va-B-$;O=za-D-Ma;Va=null;l(aa,function(a){a.isDirty=true;a.setScale()});l(V,function(a){a.isDirty=true});k.isDirtyLegend=true;k.isDirtyBox=true;Ib();d&&d.align(null,null,ba);e&&e.align(null,null,ba);i(c);Ta=null;da(k,"resize");Ab===false?x():setTimeout(x,Ab&&Ab.duration||500)};
kc=function(){k.plotLeft=B=y(B);k.plotTop=D=y(D);k.plotWidth=S=y(va-B-$);k.plotHeight=O=y(za-D-Ma);k.plotSizeX=M?O:S;k.plotSizeY=M?S:O;ba={x:fa,y:Qa,width:va-fa-cb,height:za-Qa-db}};jc=function(){D=n(p,Qa);$=n(u,cb);Ma=n(Da,db);B=n(Wa,fa);ka=[0,0,0,0]};gc=function(){var a=o.borderWidth||0,b=o.backgroundColor,c=o.plotBackgroundColor,d=o.plotBackgroundImage,e,f={x:B,y:D,width:S,height:O};e=a+(o.shadow?8:0);if(a||b)xb?xb.animate(xb.crisp(null,null,null,va-e,za-e)):xb=H.rect(e/2,e/2,va-e,za-e,o.borderRadius,
a).attr({stroke:o.borderColor,"stroke-width":a,fill:b||qa}).add().shadow(o.shadow);c&&(Aa?Aa.animate(f):Aa=H.rect(B,D,S,O,0).attr({fill:c}).add().shadow(o.plotShadow));d&&(Xa?Xa.animate(f):Xa=H.image(d,B,D,S,O).add());o.plotBorderWidth&&(Ea?Ea.animate(Ea.crisp(null,B,D,S,O)):Ea=H.rect(B,D,S,O,0,o.plotBorderWidth).attr({stroke:o.plotBorderColor,"stroke-width":o.plotBorderWidth,zIndex:4}).add());k.isDirtyBox=false};ea(ia,"unload",r);o.reflow!==false&&ea(k,"load",N);if(z)for(Za in z)ea(k,Za,z[Za]);k.options=
a;k.series=V;k.addSeries=function(a,b,c){var d;a&&(qb(c,k),b=n(b,true),da(k,"addSeries",{options:a},function(){d=g(a);d.isDirty=true;k.isDirtyLegend=true;b&&k.redraw()}));return d};k.animation=n(o.animation,true);k.destroy=r;k.get=function(a){var b,c,d;for(b=0;b<aa.length;b++)if(aa[b].options.id===a)return aa[b];for(b=0;b<V.length;b++)if(V[b].options.id===a)return V[b];for(b=0;b<V.length;b++){d=V[b].data;for(c=0;c<d.length;c++)if(d[c].id===a)return d[c]}return null};k.getSelectedPoints=function(){var a=
[];l(V,function(b){a=a.concat(lc(b.data,function(a){return a.selected}))});return a};k.getSelectedSeries=function(){return lc(V,function(a){return a.selected})};k.hideLoading=function(){Xb(jb,{opacity:0},{duration:a.loading.hideDuration,complete:function(){A(jb,{display:qa})}});kb=false};k.isInsidePlot=gb;k.redraw=i;k.setSize=ic;k.setTitle=m;k.showLoading=function(b){var c=a.loading;jb||(jb=pa($a,{className:"highcharts-loading"},F(c.style,{left:B+ma,top:D+ma,width:S+ma,height:O+ma,zIndex:10,display:qa}),
I),nb=pa("span",null,c.labelStyle,jb));nb.innerHTML=b||a.lang.loading;kb||(A(jb,{opacity:0,display:""}),Xb(jb,{opacity:c.style.opacity},{duration:c.showDuration}),kb=true)};k.pointCount=0;k.counters=new oc;E()}var C=document,ia=window,U=Math,y=U.round,Ha=U.floor,cc=U.ceil,W=U.max,Ka=U.min,ya=U.abs,fa=U.cos,ka=U.sin,na=U.PI,Yb=na*2/360,Sa=navigator.userAgent,Lb=/msie/i.test(Sa)&&!ia.opera,Ta=C.documentMode===8,vc=/AppleWebKit/.test(Sa),xc=/Firefox/.test(Sa),Kb=!!C.createElementNS&&!!C.createElementNS("http://www.w3.org/2000/svg",
"svg").createSVGRect,Fc=xc&&parseInt(Sa.split("Firefox/")[1],10)<4,Wb,Oa=C.documentElement.ontouchstart!==void 0,yc={},hc=0,La=1,Za,ra,Sb,Ab,Aa,oa,$a="div",ib="absolute",wc="relative",Ja="hidden",wb="highcharts-",Pa="visible",ma="px",qa="none",ua="M",Z="L",zc="rgba(192,192,192,"+(Kb?1.0E-6:0.0020)+")",Y="",wa="hover",Mb,Zb,$b,ac,Cb,Nb,Ob,qc,rc,bc,sc,tc,Xa=ia.HighchartsAdapter,R=Xa||{},l=R.each,lc=R.grep,vb=R.map,Q=R.merge,ea=R.addEvent,Na=R.removeEvent,da=R.fireEvent,Xb=R.animate,Jb=R.stop,ja={};
Sb=function(a,b,c){function d(a){return a.toString().replace(/^([0-9])$/,"0$1")}if(!q(b)||isNaN(b))return"Invalid date";var a=n(a,"%Y-%m-%d %H:%M:%S"),b=new Date(b*La),e,f=b[$b](),g=b[ac](),h=b[Cb](),i=b[Nb](),j=b[Ob](),m=ra.lang,l=m.weekdays,b={a:l[g].substr(0,3),A:l[g],d:d(h),e:h,b:m.shortMonths[i],B:m.months[i],m:d(i+1),y:j.toString().substr(2,2),Y:j,H:d(f),I:d(f%12||12),l:f%12||12,M:d(b[Zb]()),p:f<12?"AM":"PM",P:f<12?"am":"pm",S:d(b.getSeconds())};for(e in b)a=a.replace("%"+e,b[e]);return c?a.substr(0,
1).toUpperCase()+a.substr(1):a};oc.prototype={wrapColor:function(a){if(this.color>=a)this.color=0},wrapSymbol:function(a){if(this.symbol>=a)this.symbol=0}};Aa={init:function(a,b,c){var b=b||"",d=a.shift,e=b.indexOf("C")>-1,f=e?7:3,g,b=b.split(" "),c=[].concat(c),h,i,j=function(a){for(g=a.length;g--;)a[g]===ua&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(j(b),j(c));a.isArea&&(h=b.splice(b.length-6,6),i=c.splice(c.length-6,6));if(d)c=[].concat(c).splice(0,f).concat(c),a.shift=false;if(b.length)for(a=
c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(i));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(c===1)e=d;else if(f===b.length&&c<1)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};Xa&&Xa.init&&Xa.init(Aa);if(!Xa&&ia.jQuery){var ba=jQuery,l=function(a,b){for(var c=0,d=a.length;c<d;c++)if(b.call(a[c],a[c],c,a)===false)return c},lc=ba.grep,vb=function(a,b){for(var c=
[],d=0,e=a.length;d<e;d++)c[d]=b.call(a[d],a[d],d,a);return c},Q=function(){var a=arguments;return ba.extend(true,null,a[0],a[1],a[2],a[3])},ea=function(a,b,c){ba(a).bind(b,c)},Na=function(a,b,c){var d=C.removeEventListener?"removeEventListener":"detachEvent";C[d]&&!a[d]&&(a[d]=function(){});ba(a).unbind(b,c)},da=function(a,b,c,d){var e=ba.Event(b),f="detached"+b;F(e,c);a[b]&&(a[f]=a[b],a[b]=null);ba(a).trigger(e);a[f]&&(a[b]=a[f],a[f]=null);d&&!e.isDefaultPrevented()&&d(e)},Xb=function(a,b,c){var d=
ba(a);if(b.d)a.toD=b.d,b.d=1;d.stop();d.animate(b,c)},Jb=function(a){ba(a).stop()};ba.extend(ba.easing,{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}});var Gc=jQuery.fx.step._default,Hc=jQuery.fx.prototype.cur;ba.fx.step._default=function(a){var b=a.elem;b.attr?b.attr(a.prop,a.now):Gc.apply(this,arguments)};ba.fx.step.d=function(a){var b=a.elem;if(!a.started){var c=Aa.init(b,b.d,b.toD);a.start=c[0];a.end=c[1];a.started=true}b.attr("d",Aa.step(a.start,a.end,a.pos,b.toD))};ba.fx.prototype.cur=
function(){var a=this.elem;return a.attr?a.attr(this.prop):Hc.apply(this,arguments)}}var kb={enabled:true,align:"center",x:0,y:15,style:{color:"#666",fontSize:"11px",lineHeight:"14px"}};ra={colors:"#4572A7,#AA4643,#89A54E,#80699B,#3D96AE,#DB843D,#92A8CD,#A47D7C,#B5CA92".split(","),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),shortMonths:"Jan,Feb,Mar,Apr,May,June,Jul,Aug,Sep,Oct,Nov,Dec".split(","),
weekdays:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),decimalPoint:".",resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:true},chart:{borderColor:"#4572A7",borderRadius:5,defaultSeriesType:"line",ignoreHiddenSeries:true,spacingTop:10,spacingRight:10,spacingBottom:15,spacingLeft:10,style:{fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif',fontSize:"12px"},backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0"},
title:{text:"Chart title",align:"center",y:15,style:{color:"#3E576F",fontSize:"16px"}},subtitle:{text:"",align:"center",y:30,style:{color:"#6D869F"}},plotOptions:{line:{allowPointSelect:false,showCheckbox:false,animation:{duration:1E3},events:{},lineWidth:2,shadow:true,marker:{enabled:true,lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:Q(kb,{enabled:false,y:-6,formatter:function(){return this.y}}),
showInLegend:true,states:{hover:{marker:{}},select:{marker:{}}},stickyTracking:true}},labels:{style:{position:ib,color:"#3E576F"}},legend:{enabled:true,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderWidth:1,borderColor:"#909090",borderRadius:5,shadow:false,style:{padding:"5px"},itemStyle:{cursor:"pointer",color:"#3E576F"},itemHoverStyle:{cursor:"pointer",color:"#000000"},itemHiddenStyle:{color:"#C0C0C0"},itemCheckboxStyle:{position:ib,width:"13px",height:"13px"},
symbolWidth:16,symbolPadding:5,verticalAlign:"bottom",x:0,y:0},loading:{hideDuration:100,labelStyle:{fontWeight:"bold",position:wc,top:"1em"},showDuration:100,style:{position:ib,backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:true,backgroundColor:"rgba(255, 255, 255, .85)",borderWidth:2,borderRadius:5,shadow:true,snap:Oa?25:10,style:{color:"#333333",fontSize:"12px",padding:"5px",whiteSpace:"nowrap"}},toolbar:{itemStyle:{color:"#4572A7",cursor:"pointer"}},credits:{enabled:false,
text:"",href:"",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"10px"}}};var Rb={dateTimeLabelFormats:{second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:false,gridLineColor:"#C0C0C0",labels:kb,lineColor:"#C0D0E0",lineWidth:1,max:null,min:null,minPadding:0.01,maxPadding:0.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,
minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:false,tickColor:"#C0D0E0",tickLength:5,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#6D869F",fontWeight:"bold"}},type:"linear"},dc=Q(Rb,{endOnTick:true,gridLineWidth:1,tickPixelInterval:72,showLastLabel:true,labels:{align:"right",x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:true,tickWidth:0,title:{rotation:270,
text:"Y-values"},stackLabels:{enabled:false,formatter:function(){return this.total},style:kb.style}}),Ec={labels:{align:"right",x:-8,y:null},title:{rotation:270}},Dc={labels:{align:"left",x:8,y:null},title:{rotation:90}},uc={labels:{align:"center",x:0,y:14},title:{rotation:0}},Cc=Q(uc,{labels:{y:-5}}),ga=ra.plotOptions,Ea=ga.line;ga.spline=Q(Ea);ga.scatter=Q(Ea,{lineWidth:0,states:{hover:{lineWidth:0}}});ga.area=Q(Ea,{});ga.areaspline=Q(ga.area);ga.column=Q(Ea,{borderColor:"#FFFFFF",borderWidth:1,
borderRadius:0,groupPadding:0.2,marker:null,pointPadding:0.1,minPointLength:0,states:{hover:{brightness:0.1,shadow:false},select:{color:"#C0C0C0",borderColor:"#000000",shadow:false}},dataLabels:{y:null,verticalAlign:null}});ga.bar=Q(ga.column,{dataLabels:{align:"left",x:5,y:0}});ga.pie=Q(Ea,{borderColor:"#FFFFFF",borderWidth:1,center:["50%","50%"],colorByPoint:true,dataLabels:{distance:30,enabled:true,formatter:function(){return this.point.name},y:5},legendType:"point",marker:null,size:"75%",showInLegend:false,
slicedOffset:10,states:{hover:{brightness:0.1,shadow:false}}});Bb();var Fa=function(a){var b=[],c;(function(a){(c=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/.exec(a))?b=[K(c[1]),K(c[2]),K(c[3]),parseFloat(c[4],10)]:(c=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))&&(b=[K(c[1],16),K(c[2],16),K(c[3],16),1])})(a);return{get:function(c){return b&&!isNaN(b[0])?c==="rgb"?"rgb("+b[0]+","+b[1]+","+b[2]+")":c==="a"?b[3]:"rgba("+b.join(",")+")":
a},brighten:function(a){if(ca(a)&&a!==0){var c;for(c=0;c<3;c++)b[c]+=K(a*255),b[c]<0&&(b[c]=0),b[c]>255&&(b[c]=255)}return this},setOpacity:function(a){b[3]=a;return this}}};ab.prototype={init:function(a,b){this.element=C.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){if(b=n(b,Ab,true)){b=Q(b);if(c)b.complete=c;Xb(this,a,b)}else this.attr(a),c&&c()},attr:function(a,b){var c,d,e,f,g=this.element,h=g.nodeName,i=this.renderer,j,m=this.shadows,l=this.htmlNode,
n,x=this;Ya(a)&&q(b)&&(c=a,a={},a[c]=b);if(Ya(a))c=a,h==="circle"?c={x:"cx",y:"cy"}[c]||c:c==="strokeWidth"&&(c="stroke-width"),x=G(g,c)||this[c]||0,c!=="d"&&c!=="visibility"&&(x=parseFloat(x));else for(c in a){j=false;d=a[c];if(c==="d")d&&d.join&&(d=d.join(" ")),/(NaN| {2}|^$)/.test(d)&&(d="M 0 0"),this.d=d;else if(c==="x"&&h==="text"){for(e=0;e<g.childNodes.length;e++)f=g.childNodes[e],G(f,"x")===G(g,"x")&&G(f,"x",d);this.rotation&&G(g,"transform","rotate("+this.rotation+" "+d+" "+K(a.y||G(g,"y"))+
")")}else if(c==="fill")d=i.color(d,g,c);else if(h==="circle"&&(c==="x"||c==="y"))c={x:"cx",y:"cy"}[c]||c;else if(c==="translateX"||c==="translateY"||c==="rotation"||c==="verticalAlign")this[c]=d,this.updateTransform(),j=true;else if(c==="stroke")d=i.color(d,g,c);else if(c==="dashstyle")if(c="stroke-dasharray",d=d&&d.toLowerCase(),d==="solid")d=qa;else{if(d){d=d.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash",
"8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(e=d.length;e--;)d[e]=K(d[e])*a["stroke-width"];d=d.join(",")}}else c==="isTracker"?this[c]=d:c==="width"?d=K(d):c==="align"?(c="text-anchor",d={left:"start",center:"middle",right:"end"}[d]):c==="title"&&(e=C.createElementNS("http://www.w3.org/2000/svg","title"),e.appendChild(C.createTextNode(d)),g.appendChild(e));c==="strokeWidth"&&(c="stroke-width");vc&&c==="stroke-width"&&d===0&&(d=1.0E-6);this.symbolName&&/^(x|y|r|start|end|innerR)/.test(c)&&
(n||(this.symbolAttr(a),n=true),j=true);if(m&&/^(width|height|visibility|x|y|d)$/.test(c))for(e=m.length;e--;)G(m[e],c,d);if((c==="width"||c==="height")&&h==="rect"&&d<0)d=0;c==="text"?(this.textStr=d,this.added&&i.buildText(this)):j||G(g,c,d);if(l&&(c==="x"||c==="y"||c==="translateX"||c==="translateY"||c==="visibility")){e=l.length?l:[this];f=e.length;var t;for(t=0;t<f;t++)l=e[t],j=l.getBBox(),l=l.htmlNode,A(l,F(this.styles,{left:j.x+(this.translateX||0)+ma,top:j.y+(this.translateY||0)+ma})),c===
"visibility"&&A(l,{visibility:d})}}return x},symbolAttr:function(a){var b=this;l("x,y,r,start,end,width,height,innerR".split(","),function(c){b[c]=n(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](y(b.x*2)/2,y(b.y*2)/2,b.r,{start:b.start,end:b.end,width:b.width,height:b.height,innerR:b.innerR})})},clip:function(a){return this.attr("clip-path","url("+this.renderer.url+"#"+a.id+")")},crisp:function(a,b,c,d,e){var f,g={},h={},i,a=a||this.strokeWidth||0;i=a%2/2;h.x=Ha(b||this.x||0)+i;h.y=Ha(c||
this.y||0)+i;h.width=Ha((d||this.width||0)-2*i);h.height=Ha((e||this.height||0)-2*i);h.strokeWidth=a;for(f in h)this[f]!==h[f]&&(this[f]=g[f]=h[f]);return g},css:function(a){var b=this.element,b=a&&a.width&&b.nodeName==="text",c,d="",e=function(a,b){return"-"+b.toLowerCase()};if(a&&a.color)a.fill=a.color;this.styles=a=F(this.styles,a);if(Lb&&!Kb)b&&delete a.width,A(this.element,a);else{for(c in a)d+=c.replace(/([A-Z])/g,e)+":"+a[c]+";";this.attr({style:d})}b&&this.added&&this.renderer.buildText(this);
return this},on:function(a,b){var c=b;Oa&&a==="click"&&(a="touchstart",c=function(a){a.preventDefault();b()});this.element["on"+a]=c;return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=true;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.inverted,d=this.rotation,e=[];c&&(a+=this.attr("width"),b+=this.attr("height"));(a||b)&&e.push("translate("+a+","+b+")");c?e.push("rotate(90) scale(-1,1)"):
d&&e.push("rotate("+d+" "+this.x+" "+this.y+")");e.length&&G(this.element,"transform",e.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){a?(this.alignOptions=a,this.alignByTranslate=b,c||this.renderer.alignedObjects.push(this)):(a=this.alignOptions,b=this.alignByTranslate);var c=n(c,this.renderer),d=a.align,e=a.verticalAlign,f=(c.x||0)+(a.x||0),g=(c.y||0)+(a.y||0),h={};/^(right|center)$/.test(d)&&(f+=(c.width-(a.width||0))/{right:1,center:2}[d]);
h[b?"translateX":"x"]=y(f);/^(bottom|middle)$/.test(e)&&(g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1));h[b?"translateY":"y"]=y(g);this[this.placed?"animate":"attr"](h);this.placed=true;this.alignAttr=h;return this},getBBox:function(){var a,b,c,d=this.rotation,e=d*Yb;try{a=F({},this.element.getBBox())}catch(f){a={width:0,height:0}}b=a.width;c=a.height;if(d)a.width=ya(c*ka(e))+ya(b*fa(e)),a.height=ya(c*fa(e))+ya(b*ka(e));return a},show:function(){return this.attr({visibility:Pa})},hide:function(){return this.attr({visibility:Ja})},
add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=d.childNodes,f=this.element,g=G(f,"zIndex");this.parentInverted=a&&a.inverted;this.textStr!==void 0&&b.buildText(this);if(a&&this.htmlNode){if(!a.htmlNode)a.htmlNode=[];a.htmlNode.push(this)}if(g)c.handleZ=true,g=K(g);if(c.handleZ)for(c=0;c<e.length;c++)if(a=e[c],b=G(a,"zIndex"),a!==f&&(K(b)>g||!q(g)&&q(b)))return d.insertBefore(f,a),this;d.appendChild(f);this.added=true;return this},destroy:function(){var a=this.element||{},b=this.shadows,
c=a.parentNode,d,e;a.onclick=a.onmouseout=a.onmouseover=a.onmousemove=null;Jb(this);if(this.clipPath)this.clipPath=this.clipPath.destroy();if(this.stops){for(e=0;e<this.stops.length;e++)this.stops[e]=this.stops[e].destroy();this.stops=null}c&&c.removeChild(a);b&&l(b,function(a){(c=a.parentNode)&&c.removeChild(a)});pb(this.renderer.alignedObjects,this);for(d in this)delete this[d];return null},empty:function(){for(var a=this.element,b=a.childNodes,c=b.length;c--;)a.removeChild(b[c])},shadow:function(a,
b){var c=[],d,e,f=this.element,g=this.parentInverted?"(-1,-1)":"(1,1)";if(a){for(d=1;d<=3;d++)e=f.cloneNode(0),G(e,{isShadow:"true",stroke:"rgb(0, 0, 0)","stroke-opacity":0.05*d,"stroke-width":7-2*d,transform:"translate"+g,fill:qa}),b?b.element.appendChild(e):f.parentNode.insertBefore(e,f),c.push(e);this.shadows=c}return this}};var Vb=function(){this.init.apply(this,arguments)};Vb.prototype={Element:ab,init:function(a,b,c,d){var e=location,f;f=this.createElement("svg").attr({xmlns:"http://www.w3.org/2000/svg",
version:"1.1"});a.appendChild(f.element);this.box=f.element;this.boxWrapper=f;this.alignedObjects=[];this.url=Lb?"":e.href.replace(/#.*?$/,"");this.defs=this.createElement("defs").add();this.forExport=d;this.gradients=[];this.setSize(b,c,false)},destroy:function(){var a,b=this.gradients,c=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();if(b){for(a=0;a<b.length;a++)this.gradients[a]=b[a].destroy();this.gradients=null}if(c)this.defs=c.destroy();return this.alignedObjects=null},createElement:function(a){var b=
new this.Element;b.init(this,a);return b},buildText:function(a){for(var b=a.element,c=n(a.textStr,"").toString().replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br.*?>/g),d=b.childNodes,e=/style="([^"]+)"/,f=/href="([^"]+)"/,g=G(b,"x"),h=a.styles,i=h&&a.useHTML&&!this.forExport,j=a.htmlNode,m=h&&K(h.width),w=h&&h.lineHeight,q,x=d.length;x--;)b.removeChild(d[x]);
m&&!a.added&&this.box.appendChild(b);l(c,function(c,d){var h,i=0,j,c=c.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");h=c.split("|||");l(h,function(c){if(c!==""||h.length===1){var l={},n=C.createElementNS("http://www.w3.org/2000/svg","tspan");e.test(c)&&G(n,"style",c.match(e)[1].replace(/(;| |^)color([ :])/,"$1fill$2"));f.test(c)&&(G(n,"onclick",'location.href="'+c.match(f)[1]+'"'),A(n,{cursor:"pointer"}));c=(c.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,"<").replace(/&gt;/g,">");
n.appendChild(C.createTextNode(c));i?l.dx=3:l.x=g;if(!i){if(d){!Kb&&a.renderer.forExport&&A(n,{display:"block"});j=ia.getComputedStyle&&K(ia.getComputedStyle(q,null).getPropertyValue("line-height"));if(!j||isNaN(j))j=w||q.offsetHeight||18;G(n,"dy",j)}q=n}G(n,l);b.appendChild(n);i++;if(m)for(var c=c.replace(/-/g,"- ").split(" "),t,x=[];c.length||x.length;)t=b.getBBox().width,l=t>m,!l||c.length===1?(c=x,x=[],c.length&&(n=C.createElementNS("http://www.w3.org/2000/svg","tspan"),G(n,{dy:w||16,x:g}),b.appendChild(n),
t>m&&(m=t))):(n.removeChild(n.firstChild),x.unshift(c.pop())),c.length&&n.appendChild(C.createTextNode(c.join(" ").replace(/- /g,"-")))}})});if(i){if(!j)j=a.htmlNode=pa("span",null,F(h,{position:ib,top:0,left:0}),this.box.parentNode);j.innerHTML=a.textStr;for(x=d.length;x--;)d[x].style.visibility=Ja}},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=y(a[1])+b%2/2);a[2]===a[5]&&(a[2]=a[5]=y(a[2])+b%2/2);return a},path:function(a){return this.createElement("path").attr({d:a,fill:qa})},circle:function(a,
b,c){a=xa(a)?a:{x:a,y:b,r:c};return this.createElement("circle").attr(a)},arc:function(a,b,c,d,e,f){if(xa(a))b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x;return this.symbol("arc",a||0,b||0,c||0,{innerR:d||0,start:e||0,end:f||0})},rect:function(a,b,c,d,e,f){if(xa(a))b=a.y,c=a.width,d=a.height,e=a.r,f=a.strokeWidth,a=a.x;e=this.createElement("rect").attr({rx:e,ry:e,fill:qa});return e.attr(e.crisp(f,a,b,W(c,0),W(d,0)))},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=
b;for(this.boxWrapper[n(c,true)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return q(a)?b.attr({"class":wb+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:qa};arguments.length>1&&F(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e){var f,g=this.symbols[a],
g=g&&g(y(b),y(c),d,e),h=/^url\((.*?)\)$/,i;if(g)f=this.path(g),F(f,{symbolName:a,x:b,y:c,r:d}),e&&F(f,e);else if(h.test(a)){var j=function(a,b){a.attr({width:b[0],height:b[1]}).translate(-y(b[0]/2),-y(b[1]/2))};i=a.match(h)[1];a=yc[i];f=this.image(i).attr({x:b,y:c});a?j(f,a):(f.attr({width:0,height:0}),pa("img",{onload:function(){j(f,yc[i]=[this.width,this.height])},src:i}))}else f=this.circle(b,c,d);return f},symbols:{square:function(a,b,c){c*=0.707;return[ua,a-c,b-c,Z,a+c,b-c,a+c,b+c,a-c,b+c,"Z"]},
triangle:function(a,b,c){return[ua,a,b-1.33*c,Z,a+c,b+0.67*c,a-c,b+0.67*c,"Z"]},"triangle-down":function(a,b,c){return[ua,a,b+1.33*c,Z,a-c,b-0.67*c,a+c,b-0.67*c,"Z"]},diamond:function(a,b,c){return[ua,a,b-c,Z,a+c,b,a,b+c,a-c,b,"Z"]},arc:function(a,b,c,d){var e=d.start,f=d.end-1.0E-6,g=d.innerR,h=fa(e),i=ka(e),j=fa(f),f=ka(f),d=d.end-e<na?0:1;return[ua,a+c*h,b+c*i,"A",c,c,0,d,1,a+c*j,b+c*f,Z,a+g*j,b+g*f,"A",g,g,0,d,0,a+g*h,b+g*i,"Z"]}},clipRect:function(a,b,c,d){var e=wb+hc++,f=this.createElement("clipPath").attr({id:e}).add(this.defs),
a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f=this,b=a.linearGradient,c=wb+hc++,g,h,i;g=f.createElement("linearGradient").attr({id:c,gradientUnits:"userSpaceOnUse",x1:b[0],y1:b[1],x2:b[2],y2:b[3]}).add(f.defs);f.gradients.push(g);g.stops=[];l(a.stops,function(a){e.test(a[1])?(d=Fa(a[1]),h=d.get("rgb"),i=d.get("a")):(h=a[1],i=1);a=f.createElement("stop").attr({offset:a[0],"stop-color":h,"stop-opacity":i}).add(g);g.stops.push(a)});
return"url("+this.url+"#"+c+")"}else return e.test(a)?(d=Fa(a),G(b,c+"-opacity",d.get("a")),d.get("rgb")):(b.removeAttribute(c+"-opacity"),a)},text:function(a,b,c,d){var e=ra.chart.style,b=y(n(b,0)),c=y(n(c,0)),a=this.createElement("text").attr({x:b,y:c,text:a}).css({fontFamily:e.fontFamily,fontSize:e.fontSize});a.x=b;a.y=c;a.useHTML=d;return a}};Wb=Vb;var lb;if(!Kb){var Ic=$(ab,{init:function(a,b){var c=["<",b,' filled="f" stroked="f"'],d=["position: ",ib,";"];(b==="shape"||b===$a)&&d.push("left:0;top:0;width:10px;height:10px;");
Ta&&d.push("visibility: ",b===$a?Ja:Pa);c.push(' style="',d.join(""),'"/>');if(b)c=b===$a||b==="span"||b==="img"?c.join(""):a.prepVML(c),this.element=pa(c);this.renderer=a},add:function(a){var b=this.renderer,c=this.element,d=b.box,d=a?a.element||a:d;a&&a.inverted&&b.invertChild(c,d);Ta&&d.gVis===Ja&&A(c,{visibility:Ja});d.appendChild(c);this.added=true;this.alignOnAdd&&this.updateTransform();return this},attr:function(a,b){var c,d,e,f=this.element||{},g=f.style,h=f.nodeName,i=this.renderer,j=this.symbolName,
m,l,n=this.shadows,x=this;Ya(a)&&q(b)&&(c=a,a={},a[c]=b);if(Ya(a))c=a,x=c==="strokeWidth"||c==="stroke-width"?this.strokeweight:this[c];else for(c in a){d=a[c];m=false;if(j&&/^(x|y|r|start|end|width|height|innerR)/.test(c))l||(this.symbolAttr(a),l=true),m=true;else if(c==="d"){d=d||[];this.d=d.join(" ");e=d.length;for(m=[];e--;)m[e]=ca(d[e])?y(d[e]*10)-5:d[e]==="Z"?"x":d[e];d=m.join(" ")||"x";f.path=d;if(n)for(e=n.length;e--;)n[e].path=d;m=true}else if(c==="zIndex"||c==="visibility"){if(Ta&&c==="visibility"&&
h==="DIV"){f.gVis=d;m=f.childNodes;for(e=m.length;e--;)A(m[e],{visibility:d});d===Pa&&(d=null)}d&&(g[c]=d);m=true}else if(/^(width|height)$/.test(c))this[c]=d,this.updateClipping?(this[c]=d,this.updateClipping()):g[c]=d,m=true;else if(/^(x|y)$/.test(c))this[c]=d,f.tagName==="SPAN"?this.updateTransform():g[{x:"left",y:"top"}[c]]=d;else if(c==="class")f.className=d;else if(c==="stroke")d=i.color(d,f,c),c="strokecolor";else if(c==="stroke-width"||c==="strokeWidth")f.stroked=d?true:false,c="strokeweight",
this[c]=d,ca(d)&&(d+=ma);else if(c==="dashstyle")(f.getElementsByTagName("stroke")[0]||pa(i.prepVML(["<stroke/>"]),null,null,f))[c]=d||"solid",this.dashstyle=d,m=true;else if(c==="fill")h==="SPAN"?g.color=d:(f.filled=d!==qa?true:false,d=i.color(d,f,c),c="fillcolor");else if(c==="translateX"||c==="translateY"||c==="rotation"||c==="align")c==="align"&&(c="textAlign"),this[c]=d,this.updateTransform(),m=true;else if(c==="text")this.bBox=null,f.innerHTML=d,m=true;if(n&&c==="visibility")for(e=n.length;e--;)n[e].style[c]=
d;m||(Ta?f[c]=d:G(f,c,d))}return x},clip:function(a){var b=this,c=a.members;c.push(b);b.destroyClip=function(){pb(c,b)};return b.css(a.getCSS(b.inverted))},css:function(a){var b=this.element;if(b=a&&b.tagName==="SPAN"&&a.width)delete a.width,this.textWidth=b,this.updateTransform();this.styles=F(this.styles,a);A(this.element,a);return this},destroy:function(){this.destroyClip&&this.destroyClip();return ab.prototype.destroy.apply(this)},empty:function(){for(var a=this.element.childNodes,b=a.length,
c;b--;)c=a[b],c.parentNode.removeChild(c)},getBBox:function(){var a=this.element,b=this.bBox;if(!b){if(a.nodeName==="text")a.style.position=ib;b=this.bBox={x:a.offsetLeft,y:a.offsetTop,width:a.offsetWidth,height:a.offsetHeight}}return b},on:function(a,b){this.element["on"+a]=function(){var a=ia.event;a.target=a.srcElement;b(a)};return this},updateTransform:function(){if(this.added){var a=this,b=a.element,c=a.translateX||0,d=a.translateY||0,e=a.x||0,f=a.y||0,g=a.textAlign||"left",h={left:0,center:0.5,
right:1}[g],i=g&&g!=="left";(c||d)&&a.css({marginLeft:c,marginTop:d});a.inverted&&l(b.childNodes,function(c){a.renderer.invertChild(c,b)});if(b.tagName==="SPAN"){var j,m,c=a.rotation,n;j=0;var d=1,N=0,x;n=K(a.textWidth);var t=a.xCorr||0,r=a.yCorr||0,E=[c,g,b.innerHTML,a.textWidth].join(",");if(E!==a.cTT)q(c)&&(j=c*Yb,d=fa(j),N=ka(j),A(b,{filter:c?["progid:DXImageTransform.Microsoft.Matrix(M11=",d,", M12=",-N,", M21=",N,", M22=",d,", sizingMethod='auto expand')"].join(""):qa})),j=b.offsetWidth,m=b.offsetHeight,
j>n&&(A(b,{width:n+ma,display:"block",whiteSpace:"normal"}),j=n),n=y((K(b.style.fontSize)||12)*1.2),t=d<0&&-j,r=N<0&&-m,x=d*N<0,t+=N*n*(x?1-h:h),r-=d*n*(c?x?h:1-h:1),i&&(t-=j*h*(d<0?-1:1),c&&(r-=m*h*(N<0?-1:1)),A(b,{textAlign:g})),a.xCorr=t,a.yCorr=r;A(b,{left:e+t,top:f+r});a.cTT=E}}else this.alignOnAdd=true},shadow:function(a,b){var c=[],d,e=this.element,f=this.renderer,g,h=e.style,i,j=e.path;j&&typeof j.value!=="string"&&(j="x");if(a){for(d=1;d<=3;d++)i=['<shape isShadow="true" strokeweight="',
7-2*d,'" filled="false" path="',j,'" coordsize="100,100" style="',e.style.cssText,'" />'],g=pa(f.prepVML(i),null,{left:K(h.left)+1,top:K(h.top)+1}),i=['<stroke color="black" opacity="',0.05*d,'"/>'],pa(f.prepVML(i),null,null,g),b?b.element.appendChild(g):e.parentNode.insertBefore(g,e),c.push(g);this.shadows=c}return this}});lb=function(){this.init.apply(this,arguments)};lb.prototype=Q(Vb.prototype,{Element:Ic,isIE8:Sa.indexOf("MSIE 8.0")>-1,init:function(a,b,c){var d;this.alignedObjects=[];d=this.createElement($a);
a.appendChild(d.element);this.box=d.element;this.boxWrapper=d;this.setSize(b,c,false);if(!C.namespaces.hcv)C.namespaces.add("hcv","urn:schemas-microsoft-com:vml"),C.createStyleSheet().cssText="hcv\\:fill, hcv\\:path, hcv\\:shape, hcv\\:stroke{ behavior:url(#default#VML); display: inline-block; } "},clipRect:function(a,b,c,d){var e=this.createElement();return F(e,{members:[],left:a,top:b,width:c,height:d,getCSS:function(a){var b=this.top,c=this.left,d=c+this.width,e=b+this.height,b={clip:"rect("+y(a?
c:b)+"px,"+y(a?e:d)+"px,"+y(a?d:e)+"px,"+y(a?b:c)+"px)"};!a&&Ta&&F(b,{width:d+ma,height:e+ma});return b},updateClipping:function(){l(e.members,function(a){a.css(e.getCSS(a.inverted))})}})},color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f,g,h=a.linearGradient,i,j,m,n;l(a.stops,function(a,b){e.test(a[1])?(d=Fa(a[1]),f=d.get("rgb"),g=d.get("a")):(f=a[1],g=1);b?(m=f,n=g):(i=f,j=g)});a=90-U.atan((h[3]-h[1])/(h[2]-h[0]))*180/na;a=["<",c,' colors="0% ',i,",100% ",m,'" angle="',a,'" opacity="',
n,'" o:opacity2="',j,'" type="gradient" focus="100%" />'];pa(this.prepVML(a),null,null,b)}else if(e.test(a)&&b.tagName!=="IMG")return d=Fa(a),a=["<",c,' opacity="',d.get("a"),'"/>'],pa(this.prepVML(a),null,null,b),d.get("rgb");else{b=b.getElementsByTagName(c);if(b.length)b[0].opacity=1;return a}},prepVML:function(a){var b=this.isIE8,a=a.join("");b?(a=a.replace("/>",' xmlns="urn:schemas-microsoft-com:vml" />'),a=a.indexOf('style="')===-1?a.replace("/>",' style="display:inline-block;behavior:url(#default#VML);" />'):
a.replace('style="','style="display:inline-block;behavior:url(#default#VML);')):a=a.replace("<","<hcv:");return a},text:function(a,b,c){var d=ra.chart.style;return this.createElement("span").attr({text:a,x:y(b),y:y(c)}).css({whiteSpace:"nowrap",fontFamily:d.fontFamily,fontSize:d.fontSize})},path:function(a){return this.createElement("shape").attr({coordsize:"100 100",d:a})},circle:function(a,b,c){return this.symbol("circle").attr({x:a,y:b,r:c})},g:function(a){var b;a&&(b={className:wb+a,"class":wb+
a});return this.createElement($a).attr(b)},image:function(a,b,c,d,e){var f=this.createElement("img").attr({src:a});arguments.length>1&&f.css({left:b,top:c,width:d,height:e});return f},rect:function(a,b,c,d,e,f){if(xa(a))b=a.y,c=a.width,d=a.height,e=a.r,f=a.strokeWidth,a=a.x;var g=this.symbol("rect");g.r=e;return g.attr(g.crisp(f,a,b,W(c,0),W(d,0)))},invertChild:function(a,b){var c=b.style;A(a,{flip:"x",left:K(c.width)-10,top:K(c.height)-10,rotation:-90})},symbols:{arc:function(a,b,c,d){var e=d.start,
f=d.end,g=fa(e),h=ka(e),i=fa(f),j=ka(f),d=d.innerR,m=0.07/c,l=d&&0.1/d||0;if(f-e===0)return["x"];else 2*na-f+e<m?i=-m:f-e<l&&(i=fa(e+l));return["wa",a-c,b-c,a+c,b+c,a+c*g,b+c*h,a+c*i,b+c*j,"at",a-d,b-d,a+d,b+d,a+d*i,b+d*j,a+d*g,b+d*h,"x","e"]},circle:function(a,b,c){return["wa",a-c,b-c,a+c,b+c,a+c,b,a+c,b,"e"]},rect:function(a,b,c,d){if(!q(d))return[];var e=d.width,d=d.height,f=a+e,g=b+d,c=Ka(c,e,d);return[ua,a+c,b,Z,f-c,b,"wa",f-2*c,b,f,b+2*c,f-c,b,f,b+c,Z,f,g-c,"wa",f-2*c,g-2*c,f,g,f,g-c,f-c,g,
Z,a+c,g,"wa",a,g-2*c,a+2*c,g,a+c,g,a,g-c,Z,a,b+c,"wa",a,b,a+2*c,b+2*c,a,b+c,a+c,b,"x","e"]}}});Wb=lb}Db.prototype.callbacks=[];var mb=function(){};mb.prototype={init:function(a,b){var c=a.chart.counters,d;this.series=a;this.applyOptions(b);this.pointAttr={};if(a.options.colorByPoint){d=a.chart.options.colors;if(!this.options)this.options={};this.color=this.options.color=this.color||d[c.color++];c.wrapColor(d.length)}a.chart.pointCount++;return this},applyOptions:function(a){var b=this.series;this.config=
a;if(ca(a)||a===null)this.y=a;else if(xa(a)&&!ca(a.length))F(this,a),this.options=a;else if(Ya(a[0]))this.name=a[0],this.y=a[1];else if(ca(a[0]))this.x=a[0],this.y=a[1];if(this.x===oa)this.x=b.autoIncrement()},destroy:function(){var a=this,b=a.series,c=b.chart.hoverPoints,d;b.chart.pointCount--;c&&(a.setState(),pb(c,a));if(a===b.chart.hoverPoint)a.onMouseOut();Na(a);l("graphic,tracker,group,dataLabel,connector,shadowGroup".split(","),function(b){a[b]&&a[b].destroy()});a.legendItem&&a.series.chart.legend.destroyItem(a);
for(d in a)a[d]=null},getLabelConfig:function(){return{x:this.category,y:this.y,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},select:function(a,b){var c=this,d=c.series.chart,a=n(a,!c.selected);c.firePointEvent(a?"select":"unselect",{accumulate:b},function(){c.selected=a;c.setState(a&&"select");b||l(d.getSelectedPoints(),function(a){if(a.selected&&a!==c)a.selected=false,a.setState(Y),a.firePointEvent("unselect")})})},onMouseOver:function(){var a=this.series.chart,
b=a.tooltip,c=a.hoverPoint;if(c&&c!==this)c.onMouseOut();this.firePointEvent("mouseOver");b&&!b.shared&&b.refresh(this);this.setState(wa);a.hoverPoint=this},onMouseOut:function(){this.firePointEvent("mouseOut");this.setState();this.series.chart.hoverPoint=null},tooltipFormatter:function(a){var b=this.series;return['<span style="color:'+b.color+'">',this.name||b.name,"</span>: ",!a?"<b>x = "+(this.name||this.x)+",</b> ":"","<b>",!a?"y = ":"",this.y,"</b>"].join("")},update:function(a,b,c){var d=this,
e=d.series,f=d.graphic,g=e.chart,b=n(b,true);d.firePointEvent("update",{options:a},function(){d.applyOptions(a);xa(a)&&(e.getAttribs(),f&&f.attr(d.pointAttr[e.state]));e.isDirty=true;b&&g.redraw(c)})},remove:function(a,b){var c=this,d=c.series,e=d.chart,f=d.data;qb(b,e);a=n(a,true);c.firePointEvent("remove",null,function(){pb(f,c);c.destroy();d.isDirty=true;a&&e.redraw()})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&
this.importEvents();a==="click"&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});da(this,a,b,c)},importEvents:function(){if(!this.hasImportedEvents){var a=Q(this.series.options.point,this.options).events,b;this.events=a;for(b in a)ea(this,b,a[b]);this.hasImportedEvents=true}},setState:function(a){var b=this.series,c=b.options.states,d=ga[b.type].marker&&b.options.marker,e=d&&!d.enabled,f=(d=d&&d.states[a])&&d.enabled===false,g=b.stateMarkerGraphic,h=b.chart,i=
this.pointAttr,a=a||Y;if(!(a===this.state||this.selected&&a!=="select"||c[a]&&c[a].enabled===false||a&&(f||e&&!d.enabled))){if(this.graphic)this.graphic.attr(i[a]);else{if(a){if(!g)b.stateMarkerGraphic=g=h.renderer.circle(0,0,i[a].r).attr(i[a]).add(b.group);g.translate(this.plotX,this.plotY)}if(g)g[a?"show":"hide"]()}this.state=a}}};var T=function(){};T.prototype={isCartesian:true,type:"line",pointClass:mb,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},
init:function(a,b){var c,d;d=a.series.length;this.chart=a;b=this.setOptions(b);F(this,{index:d,options:b,name:b.name||"Series "+(d+1),state:Y,pointAttr:{},visible:b.visible!==false,selected:b.selected===true});d=b.events;for(c in d)ea(this,c,d[c]);if(d&&d.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=true;this.getColor();this.getSymbol();this.setData(b.data,false)},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=n(b,a.pointStart,0);this.pointInterval=
n(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},cleanData:function(){var a=this.chart,b=this.data,c,d,e=a.smallestInterval,f,g;pc(b,function(a,b){return a.x-b.x});if(this.options.connectNulls)for(g=b.length-1;g>=0;g--)b[g].y===null&&b[g-1]&&b[g+1]&&b.splice(g,1);for(g=b.length-1;g>=0;g--)if(b[g-1]&&(f=b[g].x-b[g-1].x,f>0&&(d===oa||f<d)))d=f,c=g;if(e===oa||d<e)a.smallestInterval=d;this.closestPoints=c},getSegments:function(){var a=-1,b=[],c=this.data;l(c,function(d,
e){d.y===null?(e>a+1&&b.push(c.slice(a+1,e)),a=e):e===c.length-1&&b.push(c.slice(a+1,e+1))});this.segments=b},setOptions:function(a){var b=this.chart.options.plotOptions;return Q(b[this.type],b.series,a)},getColor:function(){var a=this.chart.options.colors,b=this.chart.counters;this.color=this.options.color||a[b.color++]||"#0000ff";b.wrapColor(a.length)},getSymbol:function(){var a=this.chart.options.symbols,b=this.chart.counters;this.symbol=this.options.marker.symbol||a[b.symbol++];b.wrapSymbol(a.length)},
addPoint:function(a,b,c,d){var e=this.data,f=this.graph,g=this.area,h=this.chart,a=(new this.pointClass).init(this,a);qb(d,h);if(f&&c)f.shift=c;if(g)g.shift=c,g.isArea=true;b=n(b,true);e.push(a);c&&e[0].remove(false);this.getAttribs();this.isDirty=true;b&&h.redraw()},setData:function(a,b){var c=this,d=c.data,e=c.initialColor,f=c.chart,g=d&&d.length||0;c.xIncrement=null;if(q(e))f.counters.color=e;for(a=vb(yb(a||[]),function(a){return(new c.pointClass).init(c,a)});g--;)d[g].destroy();c.data=a;c.cleanData();
c.getSegments();c.getAttribs();c.isDirty=true;f.isDirtyBox=true;n(b,true)&&f.redraw(false)},remove:function(a,b){var c=this,d=c.chart,a=n(a,true);if(!c.isRemoving)c.isRemoving=true,da(c,"remove",null,function(){c.destroy();d.isDirtyLegend=d.isDirtyBox=true;a&&d.redraw(b)});c.isRemoving=false},translate:function(){for(var a=this.chart,b=this.options.stacking,c=this.xAxis.categories,d=this.yAxis,e=this.data,f=e.length;f--;){var g=e[f],h=g.x,i=g.y,j=g.low,m=d.stacks[(i<0?"-":"")+this.stackKey];g.plotX=
this.xAxis.translate(h);if(b&&this.visible&&m&&m[h])j=m[h],h=j.total,j.cum=j=j.cum-i,i=j+i,b==="percent"&&(j=h?j*100/h:0,i=h?i*100/h:0),g.percentage=h?g.y*100/h:0,g.stackTotal=h;if(q(j))g.yBottom=d.translate(j,0,1,0,1);if(i!==null)g.plotY=d.translate(i,0,1,0,1);g.clientX=a.inverted?a.plotHeight-g.plotX:g.plotX;g.category=c&&c[g.x]!==oa?c[g.x]:g.x}},setTooltipPoints:function(a){var b=this.chart,c=b.inverted,d=[],e=y((c?b.plotTop:b.plotLeft)+b.plotSizeX),f,g,h=[];if(a)this.tooltipPoints=null;l(this.segments,
function(a){d=d.concat(a)});this.xAxis&&this.xAxis.reversed&&(d=d.reverse());l(d,function(a,b){f=d[b-1]?d[b-1]._high+1:0;for(g=a._high=d[b+1]?Ha((a.plotX+(d[b+1]?d[b+1].plotX:e))/2):e;f<=g;)h[c?e-f++:f++]=a});this.tooltipPoints=h},onMouseOver:function(){var a=this.chart,b=a.hoverSeries;if(Oa||!a.mouseIsDown){if(b&&b!==this)b.onMouseOut();this.options.events.mouseOver&&da(this,"mouseOver");this.tracker&&this.tracker.toFront();this.setState(wa);a.hoverSeries=this}},onMouseOut:function(){var a=this.options,
b=this.chart,c=b.tooltip,d=b.hoverPoint;if(d)d.onMouseOut();this&&a.events.mouseOut&&da(this,"mouseOut");c&&!a.stickyTracking&&c.hide();this.setState();b.hoverSeries=null},animate:function(a){var b=this.chart,c=this.clipRect,d=this.options.animation;d&&!xa(d)&&(d={});if(a){if(!c.isAnimating)c.attr("width",0),c.isAnimating=true}else c.animate({width:b.plotSizeX},d),this.animate=null},drawPoints:function(){var a,b=this.data,c=this.chart,d,e,f,g,h,i;if(this.options.marker.enabled)for(f=b.length;f--;)if(g=
b[f],d=g.plotX,e=g.plotY,i=g.graphic,e!==oa&&!isNaN(e))a=g.pointAttr[g.selected?"select":Y],h=a.r,i?i.animate({x:d,y:e,r:h}):g.graphic=c.renderer.symbol(n(g.marker&&g.marker.symbol,this.symbol),d,e,h).attr(a).add(this.group)},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={},a=a||{},b=b||{},c=c||{},d=d||{};for(f in e)g=e[f],h[f]=n(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=ga[a.type].marker?a.options.marker:a.options,c=b.states,d=c[wa],e,f=a.color,g={stroke:f,
fill:f},h=a.data,i=[],j,m=a.pointAttrToOptions,n;a.options.marker?(d.radius=d.radius||b.radius+2,d.lineWidth=d.lineWidth||b.lineWidth+1):d.color=d.color||Fa(d.color||f).brighten(d.brightness).get();i[Y]=a.convertAttribs(b,g);l([wa,"select"],function(b){i[b]=a.convertAttribs(c[b],i[Y])});a.pointAttr=i;for(f=h.length;f--;){g=h[f];if((b=g.options&&g.options.marker||g.options)&&b.enabled===false)b.radius=0;e=false;if(g.options)for(n in m)q(b[m[n]])&&(e=true);if(e){j=[];c=b.states||{};e=c[wa]=c[wa]||{};
if(!a.options.marker)e.color=Fa(e.color||g.options.color).brighten(e.brightness||d.brightness).get();j[Y]=a.convertAttribs(b,i[Y]);j[wa]=a.convertAttribs(c[wa],i[wa],j[Y]);j.select=a.convertAttribs(c.select,i.select,j[Y])}else j=i;g.pointAttr=j}},destroy:function(){var a=this,b=a.chart,c=a.clipRect,d=/\/5[0-9\.]+ (Safari|Mobile)\//.test(Sa),e,f;da(a,"destroy");Na(a);a.legendItem&&a.chart.legend.destroyItem(a);l(a.data,function(a){a.destroy()});if(c&&c!==b.clipRect)a.clipRect=c.destroy();l(["area",
"graph","dataLabelsGroup","group","tracker"],function(b){a[b]&&(e=d&&b==="group"?"hide":"destroy",a[b][e]())});if(b.hoverSeries===a)b.hoverSeries=null;pb(b.series,a);for(f in a)delete a[f]},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a,b,c=this.data,d=this.options,e=d.dataLabels,f,g=this.dataLabelsGroup,h=this.chart,i=h.renderer,j=h.inverted,m=this.type,w;w=d.stacking;var y=m==="column"||m==="bar",x=e.verticalAlign===null,t=e.y===null;y&&(w?(x&&(e=Q(e,{verticalAlign:"middle"})),
t&&(e=Q(e,{y:{top:14,middle:4,bottom:-6}[e.verticalAlign]}))):x&&(e=Q(e,{verticalAlign:"top"})));g?g.translate(h.plotLeft,h.plotTop):g=this.dataLabelsGroup=i.g("data-labels").attr({visibility:this.visible?Pa:Ja,zIndex:6}).translate(h.plotLeft,h.plotTop).add();w=e.color;w==="auto"&&(w=null);e.style.color=n(w,this.color,"black");l(c,function(c){var l=c.barX,o=l&&l+c.barW/2||c.plotX||-999,w=n(c.plotY,-999),p=c.dataLabel,u=e.align,x=t?c.y>=0?-6:12:e.y;f=e.formatter.call(c.getLabelConfig());a=(j?h.plotWidth-
w:o)+e.x;b=(j?h.plotHeight-o:w)+x;m==="column"&&(a+={left:-1,right:1}[u]*c.barW/2||0);j&&c.y<0&&(u="right",a-=10);if(p)j&&!e.y&&(b=b+K(p.styles.lineHeight)*0.9-p.getBBox().height/2),p.attr({text:f}).animate({x:a,y:b});else if(q(f))p=c.dataLabel=i.text(f,a,b).attr({align:u,rotation:e.rotation,zIndex:1}).css(e.style).add(g),j&&!e.y&&p.attr({y:b+K(p.styles.lineHeight)*0.9-p.getBBox().height/2});if(y&&d.stacking&&p)o=c.barY,w=c.barW,c=c.barH,p.align(e,null,{x:j?h.plotWidth-o-c:l,y:j?h.plotHeight-l-w:
o,width:j?c:w,height:j?w:c})})}},drawGraph:function(){var a=this,b=a.options,c=a.graph,d=[],e,f=a.area,g=a.group,h=b.lineColor||a.color,i=b.lineWidth,j=b.dashStyle,m,w=a.chart.renderer,q=a.yAxis.getThreshold(b.threshold||0),x=/^area/.test(a.type),t=[],r=[];l(a.segments,function(c){m=[];l(c,function(d,e){a.getPointSpline?m.push.apply(m,a.getPointSpline(c,d,e)):(m.push(e?Z:ua),e&&b.step&&m.push(d.plotX,c[e-1].plotY),m.push(d.plotX,d.plotY))});c.length>1?d=d.concat(m):t.push(c[0]);if(x){var e=[],f,g=
m.length;for(f=0;f<g;f++)e.push(m[f]);g===3&&e.push(Z,m[1],m[2]);if(b.stacking&&a.type!=="areaspline")for(f=c.length-1;f>=0;f--)e.push(c[f].plotX,c[f].yBottom);else e.push(Z,c[c.length-1].plotX,q,Z,c[0].plotX,q);r=r.concat(e)}});a.graphPath=d;a.singlePoints=t;if(x)e=n(b.fillColor,Fa(a.color).setOpacity(b.fillOpacity||0.75).get()),f?f.animate({d:r}):a.area=a.chart.renderer.path(r).attr({fill:e}).add(g);if(c)Jb(c),c.animate({d:d});else if(i){c={stroke:h,"stroke-width":i};if(j)c.dashstyle=j;a.graph=
w.path(d).attr(c).add(g).shadow(b.shadow)}},render:function(){var a=this,b=a.chart,c,d,e=a.options,f=e.animation,g=f&&a.animate,f=g?f&&f.duration||500:0,h=a.clipRect,i=b.renderer;if(!h&&(h=a.clipRect=!b.hasRendered&&b.clipRect?b.clipRect:i.clipRect(0,0,b.plotSizeX,b.plotSizeY),!b.clipRect))b.clipRect=h;if(!a.group)c=a.group=i.g("series"),b.inverted&&(d=function(){c.attr({width:b.plotWidth,height:b.plotHeight}).invert()},d(),ea(b,"resize",d),ea(a,"destroy",function(){Na(b,"resize",d)})),c.clip(a.clipRect).attr({visibility:a.visible?
Pa:Ja,zIndex:e.zIndex}).translate(b.plotLeft,b.plotTop).add(b.seriesGroup);a.drawDataLabels();g&&a.animate(true);a.drawGraph&&a.drawGraph();a.drawPoints();a.options.enableMouseTracking!==false&&a.drawTracker();g&&a.animate();setTimeout(function(){h.isAnimating=false;if((c=a.group)&&h!==b.clipRect&&h.renderer)c.clip(a.clipRect=b.clipRect),h.destroy()},f);a.isDirty=false},redraw:function(){var a=this.chart,b=this.group;b&&(a.inverted&&b.attr({width:a.plotWidth,height:a.plotHeight}),b.animate({translateX:a.plotLeft,
translateY:a.plotTop}));this.translate();this.setTooltipPoints(true);this.render()},setState:function(a){var b=this.options,c=this.graph,d=b.states,b=b.lineWidth,a=a||Y;if(this.state!==a)this.state=a,d[a]&&d[a].enabled===false||(a&&(b=d[a].lineWidth||b+1),c&&!c.dashstyle&&c.attr({"stroke-width":b},a?0:500))},setVisible:function(a,b){var c=this.chart,d=this.legendItem,e=this.group,f=this.tracker,g=this.dataLabelsGroup,h,i=this.data,j=c.options.chart.ignoreHiddenSeries;h=this.visible;h=(this.visible=
a=a===oa?!h:a)?"show":"hide";if(e)e[h]();if(f)f[h]();else for(e=i.length;e--;)if(f=i[e],f.tracker)f.tracker[h]();if(g)g[h]();d&&c.legend.colorizeItem(this,a);this.isDirty=true;this.options.stacking&&l(c.series,function(a){if(a.options.stacking&&a.visible)a.isDirty=true});if(j)c.isDirtyBox=true;b!==false&&c.redraw();da(this,h)},show:function(){this.setVisible(true)},hide:function(){this.setVisible(false)},select:function(a){this.selected=a=a===oa?!this.selected:a;if(this.checkbox)this.checkbox.checked=
a;da(this,a?"select":"unselect")},drawTracker:function(){var a=this,b=a.options,c=[].concat(a.graphPath),d=c.length,e=a.chart,f=e.options.tooltip.snap,g=a.tracker,h=b.cursor,h=h&&{cursor:h},i=a.singlePoints,j;if(d)for(j=d+1;j--;)c[j]===ua&&c.splice(j+1,0,c[j+1]-f,c[j+2],Z),(j&&c[j]===ua||j===d)&&c.splice(j,0,Z,c[j-2]+f,c[j-1]);for(j=0;j<i.length;j++)d=i[j],c.push(ua,d.plotX-f,d.plotY,Z,d.plotX+f,d.plotY);g?g.attr({d:c}):a.tracker=e.renderer.path(c).attr({isTracker:true,stroke:zc,fill:qa,"stroke-width":b.lineWidth+
2*f,visibility:a.visible?Pa:Ja,zIndex:b.zIndex||1}).on(Oa?"touchstart":"mouseover",function(){if(e.hoverSeries!==a)a.onMouseOver()}).on("mouseout",function(){if(!b.stickyTracking)a.onMouseOut()}).css(h).add(e.trackerGroup)}};var Jc=$(T);ja.line=Jc;var Kc=$(T,{type:"area"});ja.area=Kc;var Ac=$(T,{type:"spline",getPointSpline:function(a,b,c){var d=b.plotX,e=b.plotY,f=a[c-1],g=a[c+1],h,i,j,m;if(c&&c<a.length-1){a=f.plotY;j=g.plotX;var g=g.plotY,l;h=(1.5*d+f.plotX)/2.5;i=(1.5*e+a)/2.5;j=(1.5*d+j)/2.5;
m=(1.5*e+g)/2.5;l=(m-i)*(j-d)/(j-h)+e-m;i+=l;m+=l;i>a&&i>e?(i=W(a,e),m=2*e-i):i<a&&i<e&&(i=Ka(a,e),m=2*e-i);m>g&&m>e?(m=W(g,e),i=2*e-m):m<g&&m<e&&(m=Ka(g,e),i=2*e-m);b.rightContX=j;b.rightContY=m}c?(b=["C",f.rightContX||f.plotX,f.rightContY||f.plotY,h||d,i||e,d,e],f.rightContX=f.rightContY=null):b=[ua,d,e];return b}});ja.spline=Ac;var Lc=$(Ac,{type:"areaspline"});ja.areaspline=Lc;var nb=$(T,{type:"column",pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color",r:"borderRadius"},
init:function(){T.prototype.init.apply(this,arguments);var a=this,b=a.chart;b.hasColumn=true;b.hasRendered&&l(b.series,function(b){if(b.type===a.type)b.isDirty=true})},translate:function(){var a=this,b=a.chart,c=a.options,d=c.stacking,e=c.borderWidth,f=0,g=a.xAxis.reversed,h=a.xAxis.categories,i={},j,m;T.prototype.translate.apply(a);l(b.series,function(b){if(b.type===a.type&&b.visible)b.options.stacking?(j=b.stackKey,i[j]===oa&&(i[j]=f++),m=i[j]):m=f++,b.columnIndex=m});var w=a.data,y=a.closestPoints,
h=ya(w[1]?w[y].plotX-w[y-1].plotX:b.plotSizeX/(h&&h.length||1)),y=h*c.groupPadding,x=(h-2*y)/f,t=c.pointWidth,r=q(t)?(x-t)/2:x*c.pointPadding,E=W(n(t,x-2*r),1),o=r+(y+((g?f-a.columnIndex:a.columnIndex)||0)*x-h/2)*(g?-1:1),z=a.yAxis.getThreshold(c.threshold||0),p=n(c.minPointLength,5);l(w,function(f){var g=f.plotY,h=f.yBottom||z,i=f.plotX+o,j=cc(Ka(g,h)),m=cc(W(g,h)-j),l=a.yAxis.stacks[(f.y<0?"-":"")+a.stackKey],n;d&&a.visible&&l&&l[f.x]&&l[f.x].setOffset(o,E);ya(m)<p&&(p&&(m=p,j=ya(j-z)>p?h-p:z-(g<=
z?p:0)),n=j-3);F(f,{barX:i,barY:j,barW:E,barH:m});f.shapeType="rect";g=F(b.renderer.Element.prototype.crisp.apply({},[e,i,j,E,m]),{r:c.borderRadius});e%2&&(g.y-=1,g.height+=1);f.shapeArgs=g;f.trackerArgs=q(n)&&Q(f.shapeArgs,{height:W(6,m+3),y:n})})},getSymbol:function(){},drawGraph:function(){},drawPoints:function(){var a=this,b=a.options,c=a.chart.renderer,d,e;l(a.data,function(f){var g=f.plotY;if(g!==oa&&!isNaN(g)&&f.y!==null)d=f.graphic,e=f.shapeArgs,d?(Jb(d),d.animate(e)):f.graphic=c[f.shapeType](e).attr(f.pointAttr[f.selected?
"select":Y]).add(a.group).shadow(b.shadow)})},drawTracker:function(){var a=this,b=a.chart,c=b.renderer,d,e,f=+new Date,g=a.options,h=g.cursor,i=h&&{cursor:h},j;l(a.data,function(h){e=h.tracker;d=h.trackerArgs||h.shapeArgs;delete d.strokeWidth;if(h.y!==null)e?e.attr(d):h.tracker=c[h.shapeType](d).attr({isTracker:f,fill:zc,visibility:a.visible?Pa:Ja,zIndex:g.zIndex||1}).on(Oa?"touchstart":"mouseover",function(c){j=c.relatedTarget||c.fromElement;if(b.hoverSeries!==a&&G(j,"isTracker")!==f)a.onMouseOver();
h.onMouseOver()}).on("mouseout",function(b){if(!g.stickyTracking&&(j=b.relatedTarget||b.toElement,G(j,"isTracker")!==f))a.onMouseOut()}).css(i).add(h.group||b.trackerGroup)})},animate:function(a){var b=this,c=b.data;if(!a)l(c,function(a){var c=a.graphic,a=a.shapeArgs;c&&(c.attr({height:0,y:b.yAxis.translate(0,0,1)}),c.animate({height:a.height,y:a.y},b.options.animation))}),b.animate=null},remove:function(){var a=this,b=a.chart;b.hasRendered&&l(b.series,function(b){if(b.type===a.type)b.isDirty=true});
T.prototype.remove.apply(a,arguments)}});ja.column=nb;var Mc=$(nb,{type:"bar",init:function(a){a.inverted=this.inverted=true;nb.prototype.init.apply(this,arguments)}});ja.bar=Mc;var Nc=$(T,{type:"scatter",translate:function(){var a=this;T.prototype.translate.apply(a);l(a.data,function(b){b.shapeType="circle";b.shapeArgs={x:b.plotX,y:b.plotY,r:a.chart.options.tooltip.snap}})},drawTracker:function(){var a=this,b=a.options.cursor,c=b&&{cursor:b},d;l(a.data,function(b){(d=b.graphic)&&d.attr({isTracker:true}).on("mouseover",
function(){a.onMouseOver();b.onMouseOver()}).on("mouseout",function(){if(!a.options.stickyTracking)a.onMouseOut()}).css(c)})},cleanData:function(){}});ja.scatter=Nc;var Oc=$(mb,{init:function(){mb.prototype.init.apply(this,arguments);var a=this,b;F(a,{visible:a.visible!==false,name:n(a.name,"Slice")});b=function(){a.slice()};ea(a,"select",b);ea(a,"unselect",b);return a},setVisible:function(a){var b=this.series.chart,c=this.tracker,d=this.dataLabel,e=this.connector,f=this.shadowGroup,g;g=(this.visible=
a=a===oa?!this.visible:a)?"show":"hide";this.group[g]();if(c)c[g]();if(d)d[g]();if(e)e[g]();if(f)f[g]();this.legendItem&&b.legend.colorizeItem(this,a)},slice:function(a,b,c){var d=this.series.chart,e=this.slicedTranslation;qb(c,d);n(b,true);a=this.sliced=q(a)?a:!this.sliced;a={translateX:a?e[0]:d.plotLeft,translateY:a?e[1]:d.plotTop};this.group.animate(a);this.shadowGroup&&this.shadowGroup.animate(a)}}),Pc=$(T,{type:"pie",isCartesian:false,pointClass:Oc,pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",
fill:"color"},getColor:function(){this.initialColor=this.chart.counters.color},animate:function(){var a=this;l(a.data,function(b){var c=b.graphic,b=b.shapeArgs,d=-na/2;c&&(c.attr({r:0,start:d,end:d}),c.animate({r:b.r,start:b.start,end:b.end},a.options.animation))});a.animate=null},translate:function(){var a=0,b=-0.25,c=this.options,d=c.slicedOffset,e=d+c.borderWidth,f=c.center.concat([c.size,c.innerSize||0]),g=this.chart,h=g.plotWidth,i=g.plotHeight,j,m,n,q=this.data,x=2*na,t,r=Ka(h,i),E,o,z,p=c.dataLabels.distance,
f=vb(f,function(a,b){return(E=/%$/.test(a))?[h,i,r,r][b]*K(a)/100:a});this.getX=function(a,b){n=U.asin((a-f[1])/(f[2]/2+p));return f[0]+(b?-1:1)*fa(n)*(f[2]/2+p)};this.center=f;l(q,function(b){a+=b.y});l(q,function(c){t=a?c.y/a:0;j=y(b*x*1E3)/1E3;b+=t;m=y(b*x*1E3)/1E3;c.shapeType="arc";c.shapeArgs={x:f[0],y:f[1],r:f[2]/2,innerR:f[3]/2,start:j,end:m};n=(m+j)/2;c.slicedTranslation=vb([fa(n)*d+g.plotLeft,ka(n)*d+g.plotTop],y);o=fa(n)*f[2]/2;z=ka(n)*f[2]/2;c.tooltipPos=[f[0]+o*0.7,f[1]+z*0.7];c.labelPos=
[f[0]+o+fa(n)*p,f[1]+z+ka(n)*p,f[0]+o+fa(n)*e,f[1]+z+ka(n)*e,f[0]+o,f[1]+z,p<0?"center":n<x/4?"left":"right",n];c.percentage=t*100;c.total=a});this.setTooltipPoints()},render:function(){this.drawPoints();this.options.enableMouseTracking!==false&&this.drawTracker();this.drawDataLabels();this.options.animation&&this.animate&&this.animate();this.isDirty=false},drawPoints:function(){var a=this.chart,b=a.renderer,c,d,e,f=this.options.shadow,g,h;l(this.data,function(i){d=i.graphic;h=i.shapeArgs;e=i.group;
g=i.shadowGroup;if(f&&!g)g=i.shadowGroup=b.g("shadow").attr({zIndex:4}).add();if(!e)e=i.group=b.g("point").attr({zIndex:5}).add();c=i.sliced?i.slicedTranslation:[a.plotLeft,a.plotTop];e.translate(c[0],c[1]);g&&g.translate(c[0],c[1]);d?d.animate(h):i.graphic=b.arc(h).attr(F(i.pointAttr[Y],{"stroke-linejoin":"round"})).add(i.group).shadow(f,g);i.visible===false&&i.setVisible(false)})},drawDataLabels:function(){var a=this.data,b,c=this.chart,d=this.options.dataLabels,e=n(d.connectorPadding,10),f=n(d.connectorWidth,
1),g,h,i=n(d.softConnector,true),j=d.distance,m=this.center,q=m[2]/2,m=m[1],y=j>0,x=[[],[]],t,r,E,o,z=2,p;if(d.enabled){T.prototype.drawDataLabels.apply(this);l(a,function(a){a.dataLabel&&x[a.labelPos[7]<na/2?0:1].push(a)});x[1].reverse();o=function(a,b){return b.y-a.y};for(a=x[0][0]&&x[0][0].dataLabel&&K(x[0][0].dataLabel.styles.lineHeight);z--;){var u=[],C=[],F=x[z],G=F.length,A;for(p=m-q-j;p<=m+q+j;p+=a)u.push(p);E=u.length;if(G>E){h=[].concat(F);h.sort(o);for(p=G;p--;)h[p].rank=p;for(p=G;p--;)F[p].rank>=
E&&F.splice(p,1);G=F.length}for(p=0;p<G;p++){b=F[p];h=b.labelPos;b=9999;for(r=0;r<E;r++)g=ya(u[r]-h[1]),g<b&&(b=g,A=r);if(A<p&&u[p]!==null)A=p;else for(E<G-p+A&&u[p]!==null&&(A=E-G+p);u[A]===null;)A++;C.push({i:A,y:u[A]});u[A]=null}C.sort(o);for(p=0;p<G;p++){b=F[p];h=b.labelPos;g=b.dataLabel;r=C.pop();t=h[1];E=b.visible===false?Ja:Pa;A=r.i;r=r.y;if(t>r&&u[A+1]!==null||t<r&&u[A-1]!==null)r=t;t=this.getX(A===0||A===u.length-1?t:r,z);g.attr({visibility:E,align:h[6]})[g.moved?"animate":"attr"]({x:t+d.x+
({left:e,right:-e}[h[6]]||0),y:r+d.y});g.moved=true;if(y&&f)g=b.connector,h=i?[ua,t+(h[6]==="left"?5:-5),r,"C",t,r,2*h[2]-h[4],2*h[3]-h[5],h[2],h[3],Z,h[4],h[5]]:[ua,t+(h[6]==="left"?5:-5),r,Z,h[2],h[3],Z,h[4],h[5]],g?(g.animate({d:h}),g.attr("visibility",E)):b.connector=g=this.chart.renderer.path(h).attr({"stroke-width":f,stroke:d.connectorColor||b.color||"#606060",visibility:E,zIndex:3}).translate(c.plotLeft,c.plotTop).add()}}}},drawTracker:nb.prototype.drawTracker,getSymbol:function(){}});ja.pie=
Pc;ia.Highcharts={Chart:Db,dateFormat:Sb,pathAnim:Aa,getOptions:function(){return ra},hasRtlBug:Fc,numberFormat:mc,Point:mb,Color:Fa,Renderer:Wb,seriesTypes:ja,setOptions:function(a){ra=Q(ra,a);Bb();return ra},Series:T,addEvent:ea,createElement:pa,discardElement:Pb,css:A,each:l,extend:F,map:vb,merge:Q,pick:n,extendClass:$,product:"Highcharts",version:"2.1.7"}})();
